//! expect-stdout: ok

use std.build

fn sample_action(ctx: ActionCtx) -> i32:
    0

fn main:
    let pkg = Package { name: "demo", version: "0.1.0" }
    var b = new_build(pkg)
    var exe = target_new(.Executable, "demo", "src/main.w")
    exe = exe.optimize(OptimizeMode.debug)
    exe = exe.link_system_lib("m")
    b = b.add_target(exe)
    assert(b.targets.len() == 1)
    let recorded = b.targets.get(0)
    assert((recorded.kind as i32) == 0)
    assert(recorded.name == "demo")
    assert(recorded.entry == "src/main.w")
    assert(recorded.output == "")
    assert(recorded.optimize_mode == OptimizeMode.debug)
    assert(recorded.system_libs.len() == 1)
    assert(recorded.system_libs.get(0) == "m")
    b = b.library("demo_lib", "src/lib.w")
    assert(b.targets.len() == 2)
    assert((b.targets.get(1).kind as i32) == 1)
    b = b.object("demo_obj", "src/main.w")
    assert(b.targets.len() == 3)
    let obj = b.targets.get(2)
    assert((obj.kind as i32) == 3)
    assert(obj.entry == "src/main.w")
    b = b.archive("demo_archive", "src/lib.w")
    assert(b.targets.len() == 4)
    let archive_product = b.targets.get(3)
    assert((archive_product.kind as i32) == 4)
    assert(archive_product.entry == "src/lib.w")
    b = b.compile_c_object("helper-o", "runtime/helper.c", "out/lib/helper.o")
    assert(b.targets.len() == 5)
    let cobj = b.targets.get(4)
    assert((cobj.kind as i32) == 12)
    assert(cobj.entry == "runtime/helper.c")
    assert(cobj.output == "out/lib/helper.o")
    b = b.binary_compare("fix", "out/a.o", "out/b.o")
    assert(b.targets.len() == 6)
    let cmp = b.targets.get(5)
    assert((cmp.kind as i32) == 10)
    assert(cmp.args.len() == 1)
    assert(cmp.args.get(0) == "out/b.o")
    b = b.command("run-demo", "out/bin/demo")
    assert(b.targets.len() == 7)
    let command = b.targets.get(6)
    assert((command.kind as i32) == 7)
    assert(command.entry == "out/bin/demo")
    b = b.install("install-demo", "out/bin/demo", "out/install/demo")
    assert(b.targets.len() == 8)
    let install = b.targets.get(7)
    assert((install.kind as i32) == 8)
    assert(install.entry == "out/bin/demo")
    assert(install.output == "out/install/demo")
    b = b.copy_tree("copy-assets", "assets", "out/assets")
    assert(b.targets.len() == 9)
    let copy_tree = b.targets.get(8)
    assert((copy_tree.kind as i32) == 18)
    assert(copy_tree.entry == "assets")
    assert(copy_tree.output == "out/assets")
    b = b.copy_file("copy-readme", "README.md", "out/README.md")
    assert(b.targets.len() == 10)
    let copy_file = b.targets.get(9)
    assert((copy_file.kind as i32) == 22)
    assert(copy_file.entry == "README.md")
    assert(copy_file.output == "out/README.md")
    var action = target_new(.Action, "generate", "").output("out/generated.txt")
    action = action.arg("hello")
    action.action = sample_action
    b = b.add_target(action)
    assert(b.targets.len() == 11)
    let action_target = b.targets.get(10)
    assert((action_target.kind as i32) == 23)
    assert(action_target.output == "out/generated.txt")
    b = b.clean("clean")
    assert(b.targets.len() == 12)
    let clean = b.targets.get(11)
    assert((clean.kind as i32) == 21)
    assert(clean.name == "clean")
    var archive = target_new(.CreateStaticArchive, "liball", "")
    archive = archive.output("out/lib/liball.a")
    archive = archive.input("out/lib/a.o")
    archive = archive.input("out/lib/b.o")
    archive = archive.dep("helper-o")
    b = b.add_target(archive)
    b = b.default("liball")
    assert(b.targets.len() == 13)
    assert(b.default_target == "liball")
    let graph = b.emit_graph()
    assert(graph.starts_with("WITH_BUILD_GRAPH\t2\n"))
    assert(graph.contains("default_target\tliball"))
    assert(graph.contains("target\t3\tdemo_obj\tsrc/main.w\t0\t0\t"))
    assert(graph.contains("target\t4\tdemo_archive\tsrc/lib.w\t0\t0\t"))
    assert(graph.contains("target\t12\thelper-o\truntime/helper.c\t0\t0\tout/lib/helper.o"))
    assert(graph.contains("arg\t5\tout/b.o"))
    assert(graph.contains("target\t7\trun-demo\tout/bin/demo\t0\t0\t"))
    assert(graph.contains("target\t8\tinstall-demo\tout/bin/demo\t0\t0\tout/install/demo"))
    assert(graph.contains("target\t18\tcopy-assets\tassets\t0\t0\tout/assets"))
    assert(graph.contains("target\t22\tcopy-readme\tREADME.md\t0\t0\tout/README.md"))
    assert(graph.contains("target\t23\tgenerate\t\t0\t0\tout/generated.txt"))
    assert(graph.contains("target\t21\tclean\t\t0\t0\t"))
    assert(graph.contains("input\t12\tout/lib/a.o"))
    assert(graph.contains("dep\t12\thelper-o"))
    print("ok")
