//! expect-stdout: ok

use std.build

fn main:
    let pkg = Package { name: "demo", version: "0.1.0" }
    var b = new_build(pkg)
    var exe = target_new(.Executable, "demo", "src/main.w")
    exe = exe.optimize(OptimizeMode.debug)
    exe = exe.link_system_lib("m")
    b = b.add_target(exe)
    assert(b.targets.len() == 1)
    let recorded = b.targets.get(0)
    assert((recorded.kind as i32) == 0)
    assert(recorded.name == "demo")
    assert(recorded.entry == "src/main.w")
    assert(recorded.output == "")
    assert(recorded.optimize_mode == OptimizeMode.debug)
    assert(recorded.system_libs.len() == 1)
    assert(recorded.system_libs.get(0) == "m")
    b = b.library("demo_lib", "src/lib.w")
    assert(b.targets.len() == 2)
    assert((b.targets.get(1).kind as i32) == 1)
    b = b.compile_c_object("helper-o", "runtime/helper.c", "out/lib/helper.o")
    assert(b.targets.len() == 3)
    let cobj = b.targets.get(2)
    assert((cobj.kind as i32) == 12)
    assert(cobj.entry == "runtime/helper.c")
    assert(cobj.output == "out/lib/helper.o")
    b = b.binary_compare("fix", "out/a.o", "out/b.o")
    assert(b.targets.len() == 4)
    let cmp = b.targets.get(3)
    assert((cmp.kind as i32) == 10)
    assert(cmp.args.len() == 1)
    assert(cmp.args.get(0) == "out/b.o")
    var archive = target_new(.CreateStaticArchive, "liball", "")
    archive = archive.output("out/lib/liball.a")
    archive = archive.input("out/lib/a.o")
    archive = archive.input("out/lib/b.o")
    archive = archive.dep("helper-o")
    b = b.add_target(archive)
    b = b.default("liball")
    assert(b.targets.len() == 5)
    assert(b.default_target == "liball")
    let graph = b.emit_graph()
    assert(graph.starts_with("WITH_BUILD_GRAPH\t2\n"))
    assert(graph.contains("default_target\tliball"))
    assert(graph.contains("target\t12\thelper-o\truntime/helper.c\t0\t0\tout/lib/helper.o"))
    assert(graph.contains("arg\t3\tout/b.o"))
    assert(graph.contains("input\t4\tout/lib/a.o"))
    assert(graph.contains("dep\t4\thelper-o"))
    print("ok")
