//! expect-stdout: ok

use std.build

fn sample_action(ctx: ActionCtx) -> i32:
    0

fn main:
    let pkg = Package { name: "demo", version: "0.1.0" }
    var b = new_build(pkg)
    var exe = target_new(.Executable, "demo", "src/main.w")
    exe = exe.optimize(OptimizeMode.debug)
    exe = exe.link_system_lib("m")
    b = b.add_target(exe)
    assert(b.targets.len() == 1)
    // Immediate view uses (pre-E3 conservative view liveness treats a
    // bound view as live to scope end; b is rebuilt below).
    assert((b.targets[0].kind as i32) == 0)
    assert(b.targets[0].name == "demo")
    assert(b.targets[0].entry == "src/main.w")
    assert(b.targets[0].output == "")
    assert(b.targets[0].optimize_mode == OptimizeMode.debug)
    assert(b.targets[0].system_libs.len() == 1)
    assert(b.targets[0].system_libs[0] == "m")
    b = b.library("demo_lib", "src/lib.w")
    assert(b.targets.len() == 2)
    assert((b.targets[1].kind as i32) == 1)
    b = b.object("demo_obj", "src/main.w")
    assert(b.targets.len() == 3)
    assert((b.targets[2].kind as i32) == 3)
    assert(b.targets[2].entry == "src/main.w")
    b = b.archive("demo_archive", "src/lib.w")
    assert(b.targets.len() == 4)
    assert((b.targets[3].kind as i32) == 4)
    assert(b.targets[3].entry == "src/lib.w")
    b = b.compile_c_object("helper-o", "runtime/helper.c", "out/lib/helper.o")
    assert(b.targets.len() == 5)
    assert((b.targets[4].kind as i32) == 12)
    assert(b.targets[4].entry == "runtime/helper.c")
    assert(b.targets[4].output == "out/lib/helper.o")
    b = b.binary_compare("fix", "out/a.o", "out/b.o")
    assert(b.targets.len() == 6)
    assert((b.targets[5].kind as i32) == 10)
    assert(b.targets[5].args.len() == 1)
    assert(b.targets[5].args[0] == "out/b.o")
    b = b.command("run-demo", "out/bin/demo")
    assert(b.targets.len() == 7)
    assert((b.targets[6].kind as i32) == 7)
    assert(b.targets[6].entry == "out/bin/demo")
    b = b.install("install-demo", "out/bin/demo", "out/install/demo")
    assert(b.targets.len() == 8)
    assert((b.targets[7].kind as i32) == 8)
    assert(b.targets[7].entry == "out/bin/demo")
    assert(b.targets[7].output == "out/install/demo")
    b = b.copy_tree("copy-assets", "assets", "out/assets")
    assert(b.targets.len() == 9)
    assert((b.targets[8].kind as i32) == 18)
    assert(b.targets[8].entry == "assets")
    assert(b.targets[8].output == "out/assets")
    b = b.copy_file("copy-readme", "README.md", "out/README.md")
    assert(b.targets.len() == 10)
    assert((b.targets[9].kind as i32) == 22)
    assert(b.targets[9].entry == "README.md")
    assert(b.targets[9].output == "out/README.md")
    var action = target_new(.Action, "generate", "").output("out/generated.txt")
    action = action.extra_output("out/generated.meta")
    action = action.arg("hello")
    action.action = sample_action
    b = b.add_target(action)
    assert(b.targets.len() == 11)
    assert((b.targets[10].kind as i32) == 23)
    assert(b.targets[10].output == "out/generated.txt")
    assert(b.targets[10].extra_outputs.len() == 1)
    assert(b.targets[10].extra_outputs[0] == "out/generated.meta")
    b = b.clean("clean")
    assert(b.targets.len() == 12)
    assert((b.targets[11].kind as i32) == 21)
    assert(b.targets[11].name == "clean")
    var archive = target_new(.CreateStaticArchive, "liball", "")
    archive = archive.output("out/lib/liball.a")
    archive = archive.input("out/lib/a.o")
    archive = archive.input("out/lib/b.o")
    archive = archive.dep("helper-o")
    b = b.add_target(archive)
    b = b.default("liball")
    assert(b.targets.len() == 13)
    assert(b.default_target == "liball")
    let graph = b.emit_graph()
    assert(graph.starts_with("WITH_BUILD_GRAPH\t2\n"))
    assert(graph.contains("default_target\tliball"))
    assert(graph.contains("target\t3\tdemo_obj\tsrc/main.w\t0\t0\t"))
    assert(graph.contains("target\t4\tdemo_archive\tsrc/lib.w\t0\t0\t"))
    assert(graph.contains("target\t12\thelper-o\truntime/helper.c\t0\t0\tout/lib/helper.o"))
    assert(graph.contains("arg\t5\tout/b.o"))
    assert(graph.contains("target\t7\trun-demo\tout/bin/demo\t0\t0\t"))
    assert(graph.contains("target\t8\tinstall-demo\tout/bin/demo\t0\t0\tout/install/demo"))
    assert(graph.contains("target\t18\tcopy-assets\tassets\t0\t0\tout/assets"))
    assert(graph.contains("target\t22\tcopy-readme\tREADME.md\t0\t0\tout/README.md"))
    assert(graph.contains("target\t23\tgenerate\t\t0\t0\tout/generated.txt"))
    assert(graph.contains("extra_output\t10\tout/generated.meta"))
    assert(graph.contains("target\t21\tclean\t\t0\t0\t"))
    assert(graph.contains("input\t12\tout/lib/a.o"))
    assert(graph.contains("dep\t12\thelper-o"))
    print("ok")
