use std.build

pub fn build(b: Build) -> Build:
    var out = b

    var compiler_sources = target_new(.GenerateCompilerEntrypoints, "compiler-sources", "").output("out/gen/.generated-stamp")
    compiler_sources = compiler_sources.input("src/main.w")
    compiler_sources = compiler_sources.input("src/bootstrap_main.w")
    compiler_sources = compiler_sources.input("src/main_emit_temp.w")
    compiler_sources = compiler_sources.input("src/version")
    out = out.add_target(compiler_sources)

    var stage1 = target_new(.WithCompilerBuild, "stage1", "seed").output("out/bin/with-stage1")
    stage1 = stage1.input("out/gen/main.w")
    stage1 = stage1.arg("-O0")
    stage1 = stage1.dep("compiler-sources")
    out = out.add_target(stage1)

    var stage2 = target_new(.WithCompilerBuild, "stage2", "out/bin/with-stage1").output("out/bin/with-stage2")
    stage2 = stage2.input("out/gen/main.w")
    stage2 = stage2.arg("-O0")
    stage2 = stage2.dep("stage1")
    out = out.add_target(stage2)

    var stage3 = target_new(.WithCompilerBuild, "stage3", "out/bin/with-stage2").output("out/bin/with-stage3")
    stage3 = stage3.input("out/gen/main.w")
    stage3 = stage3.arg("-O0")
    stage3 = stage3.dep("stage2")
    out = out.add_target(stage3)

    var stage2_fixpoint = target_new(.WithCompilerBuild, "stage2-fixpoint-object", "out/bin/with-stage1").output("out/bin/with-stage2-fixpoint.o")
    stage2_fixpoint = stage2_fixpoint.input("out/gen/main.w")
    stage2_fixpoint = stage2_fixpoint.arg("--emit-obj")
    stage2_fixpoint = stage2_fixpoint.arg("-O0")
    stage2_fixpoint = stage2_fixpoint.dep("stage1")
    out = out.add_target(stage2_fixpoint)

    var stage3_fixpoint = target_new(.WithCompilerBuild, "stage3-fixpoint-object", "out/bin/with-stage2").output("out/bin/with-stage3-fixpoint.o")
    stage3_fixpoint = stage3_fixpoint.input("out/gen/main.w")
    stage3_fixpoint = stage3_fixpoint.arg("--emit-obj")
    stage3_fixpoint = stage3_fixpoint.arg("-O0")
    stage3_fixpoint = stage3_fixpoint.dep("stage2")
    out = out.add_target(stage3_fixpoint)

    var selfcheck = target_new(.RunCorpusTest, "selfcheck", "out/bin/with-stage2")
    selfcheck = selfcheck.output("out/corpus/selfcheck")
    selfcheck = selfcheck.arg("check")
    selfcheck = selfcheck.arg("src/main.w")
    selfcheck = selfcheck.dep("stage2")
    out = out.add_target(selfcheck)

    var fixpoint = target_new(.FixpointCompare, "fixpoint", "out/bin/with-stage2-fixpoint.o")
    fixpoint = fixpoint.arg("out/bin/with-stage3-fixpoint.o")
    fixpoint = fixpoint.dep("stage2-fixpoint-object")
    fixpoint = fixpoint.dep("stage3-fixpoint-object")
    out = out.add_target(fixpoint)

    var verified = target_new(.Group, "verified-existing-stage", "")
    verified = verified.dep("selfcheck")
    verified = verified.dep("fixpoint")
    out = out.add_target(verified)

    var behavior_tests = target_new(.Test, "behavior-tests", "test/behavior/*.w")
    behavior_tests = behavior_tests.arg("compiler=out/bin/with-stage2")
    behavior_tests = behavior_tests.dep("selfcheck")
    out = out.add_target(behavior_tests)

    var native_compile_error_tests = target_new(.Test, "native-compile-error-tests", "test/compile_errors/*.w")
    native_compile_error_tests = native_compile_error_tests.dep("selfcheck")
    out = out.add_target(native_compile_error_tests)

    var native_codegen_tests = target_new(.Test, "native-codegen-tests", "test/codegen/*.w")
    native_codegen_tests = native_codegen_tests.dep("selfcheck")
    out = out.add_target(native_codegen_tests)

    var native_spec_tests = target_new(.Test, "native-spec-tests", "test/spec/*.w")
    native_spec_tests = native_spec_tests.dep("selfcheck")
    out = out.add_target(native_spec_tests)

    var native_phase_tests = target_new(.Test, "native-phase-tests", "test/phase/*.w")
    native_phase_tests = native_phase_tests.dep("selfcheck")
    out = out.add_target(native_phase_tests)

    var cli_selfhost_tests = target_new(.Command, "cli-selfhost-tests", "/usr/bin/env")
    cli_selfhost_tests = cli_selfhost_tests.input("scripts/run_cli_selfhost_tests.sh")
    cli_selfhost_tests = cli_selfhost_tests.input("out/bin/with-stage2")
    cli_selfhost_tests = cli_selfhost_tests.arg("WITH=out/bin/with-stage2")
    cli_selfhost_tests = cli_selfhost_tests.arg("scripts/run_cli_selfhost_tests.sh")
    cli_selfhost_tests = cli_selfhost_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_tests)

    var cli_selfhost_smoke_tests = target_new(.CliSelfhostSmokeTest, "cli-selfhost-smoke-tests", "out/bin/with-stage2")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.input("out/bin/with-stage2")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_smoke_tests)

    var issue61_regression = target_new(.SelfhostNoopLocalRegression, "issue61-regression", "out/bin/with-stage2")
    issue61_regression = issue61_regression.input("out/bin/with-stage2")
    issue61_regression = issue61_regression.dep("selfcheck")
    out = out.add_target(issue61_regression)

    var embedded_runtime_regression = target_new(.EmbeddedRuntimeExtractTest, "embedded-runtime-regression", "out/bin/with")
    embedded_runtime_regression = embedded_runtime_regression.input("out/bin/with")
    embedded_runtime_regression = embedded_runtime_regression.dep("selfcheck")
    out = out.add_target(embedded_runtime_regression)

    var tests = target_new(.Group, "test", "")
    tests = tests.dep("behavior-tests")
    tests = tests.dep("native-compile-error-tests")
    tests = tests.dep("native-codegen-tests")
    tests = tests.dep("native-spec-tests")
    tests = tests.dep("native-phase-tests")
    tests = tests.dep("cli-selfhost-smoke-tests")
    tests = tests.dep("cli-selfhost-tests")
    tests = tests.dep("issue61-regression")
    tests = tests.dep("embedded-runtime-regression")
    out = out.add_target(tests)

    var install_user = target_new(.Install, "install-user", "out/bin/with").output("$HOME/.local/bin/with")
    install_user = install_user.input("out/bin/with")
    install_user = install_user.arg("0755")
    install_user = install_user.dep("verified-existing-stage")
    out = out.add_target(install_user)

    var update_seed = target_new(.Install, "update-seed", "out/bin/with-stage2").output("src/main")
    update_seed = update_seed.input("out/bin/with-stage2")
    update_seed = update_seed.arg("0755")
    update_seed = update_seed.dep("verified-existing-stage")
    out = out.add_target(update_seed)

    var regex_test = target_new(.Pcre2RunTest, "regex-test", "out/pcre2_build/bin/pcre2test")
    regex_test = regex_test.input("out/pcre2_migrated")
    regex_test = regex_test.input("out/pcre2_build/bin/pcre2test")
    regex_test = regex_test.input("out/pcre2_reference/pcre2-10.47/RunTest")
    regex_test = regex_test.arg("out/pcre2_reference/pcre2-10.47")
    regex_test = regex_test.dep("verified-existing-stage")
    out = out.add_target(regex_test)

    var regex_check_generated = target_new(.Command, "regex-check-generated", "scripts/pcre2_generated_workflow.sh")
    regex_check_generated = regex_check_generated.input("scripts/pcre2_generated_workflow.sh")
    regex_check_generated = regex_check_generated.input("out/bin/with")
    regex_check_generated = regex_check_generated.input("out/pcre2_build/lib/std/re/defs.w")
    regex_check_generated = regex_check_generated.arg("check")
    regex_check_generated = regex_check_generated.arg("out/bin/with")
    regex_check_generated = regex_check_generated.arg("out/pcre2_build/lib/std/re")
    regex_check_generated = regex_check_generated.dep("verified-existing-stage")
    out = out.add_target(regex_check_generated)

    var regex_promote = target_new(.Command, "regex-promote", "scripts/pcre2_generated_workflow.sh")
    regex_promote = regex_promote.input("scripts/pcre2_generated_workflow.sh")
    regex_promote = regex_promote.input("out/bin/with")
    regex_promote = regex_promote.input("out/pcre2_build/lib/std/re/defs.w")
    regex_promote = regex_promote.arg("promote")
    regex_promote = regex_promote.arg("out/bin/with")
    regex_promote = regex_promote.arg("out/pcre2_build/lib/std/re")
    regex_promote = regex_promote.arg("lib/std/re")
    regex_promote = regex_promote.dep("regex-test")
    regex_promote = regex_promote.dep("regex-check-generated")
    out = out.add_target(regex_promote)

    out.default("verified-existing-stage")
