use std.build

fn with_object_target(name: str, compiler: str, source: str, output: str, opt: str, dep: str) -> Target:
    var target = target_new(.WithCompilerBuild, name, compiler).output(output)
    target = target.input(source)
    target = target.arg("--emit-obj")
    target = target.arg("--no-prelude")
    target = target.arg(opt)
    if dep.len() > 0:
        target = target.dep(dep)
    target

fn with_ir_target(name: str, compiler: str, source: str, output: str, dep: str) -> Target:
    var target = target_new(.WithCompilerIr, name, compiler).output(output)
    target = target.input(source)
    target = target.arg("--no-prelude")
    if dep.len() > 0:
        target = target.dep(dep)
    target

fn install_file_target(name: str, source: str, dest: str, mode: str, dep: str) -> Target:
    var target = target_new(.Install, name, source).output(dest)
    target = target.input(source)
    target = target.arg(mode)
    if dep.len() > 0:
        target = target.dep(dep)
    target

pub fn build(b: Build) -> Build:
    var out = b

    var compiler_sources = target_new(.GenerateCompilerEntrypoints, "compiler-sources", "").output("out/gen/.generated-stamp")
    compiler_sources = compiler_sources.input("src/main.w")
    compiler_sources = compiler_sources.input("src/bootstrap_main.w")
    compiler_sources = compiler_sources.input("src/main_emit_temp.w")
    compiler_sources = compiler_sources.input("src/version")
    out = out.add_target(compiler_sources)

    var compat_runtime = target_new(33 as BuildKind, "compat-runtime-source", "rt/compat_runtime.w").output("out/gen/compat_runtime.w")
    out = out.add_target(compat_runtime)

    out = out.add_target(with_object_target("bootstrap-llvm-bridge-object", "seed", "rt/llvm_bridge.w", "out/bootstrap-lib/llvm_bridge.o", "-O0", ""))
    out = out.add_target(with_object_target("bootstrap-clang-bridge-object", "seed", "rt/clang_bridge.w", "out/bootstrap-lib/clang_bridge.o", "-O0", ""))

    var bootstrap_llvm_link_metadata = target_new(41 as BuildKind, "bootstrap-llvm-link-metadata", "").output("out/bootstrap-lib/.llvm-link-ready")
    bootstrap_llvm_link_metadata = bootstrap_llvm_link_metadata.input("out/bootstrap-lib/llvm_bridge.o")
    bootstrap_llvm_link_metadata = bootstrap_llvm_link_metadata.input("out/bootstrap-lib/clang_bridge.o")
    bootstrap_llvm_link_metadata = bootstrap_llvm_link_metadata.dep("bootstrap-llvm-bridge-object")
    bootstrap_llvm_link_metadata = bootstrap_llvm_link_metadata.dep("bootstrap-clang-bridge-object")
    out = out.add_target(bootstrap_llvm_link_metadata)

    out = out.add_target(with_object_target("bootstrap-rt-core-object", "seed", "rt/rt_core.w", "out/bootstrap-lib/rt_core.o", "-O2", ""))
    out = out.add_target(with_object_target("bootstrap-rt-darwin-aarch64-object", "seed", "rt/darwin_aarch64.w", "out/bootstrap-lib/rt_darwin_aarch64.o", "-O2", ""))
    out = out.add_target(with_object_target("bootstrap-cimport-stubs-object", "seed", "rt/cimport_stubs.w", "out/bootstrap-lib/cimport_stubs.o", "-O0", ""))
    out = out.add_target(with_object_target("bootstrap-compat-runtime-object", "seed", "out/gen/compat_runtime.w", "out/bootstrap-lib/compat_runtime.o", "-O0", "compat-runtime-source"))
    out = out.add_target(with_object_target("bootstrap-panic-runtime-object", "seed", "rt/panic_runtime.w", "out/bootstrap-lib/panic_runtime.o", "-O0", ""))
    out = out.add_target(with_ir_target("bootstrap-regex-runtime-ir", "seed", "rt/regex_runtime.w", "out/bootstrap-tmp/regex_runtime.ll", ""))
    var bootstrap_regex_runtime = target_new(.CompileLlvmIrObject, "bootstrap-regex-runtime-object", "out/bootstrap-tmp/regex_runtime.ll").output("out/bootstrap-lib/regex_runtime.o")
    bootstrap_regex_runtime = bootstrap_regex_runtime.dep("bootstrap-regex-runtime-ir")
    out = out.add_target(bootstrap_regex_runtime)
    out = out.add_target(with_object_target("bootstrap-fiber-stubs-object", "seed", "rt/fiber_stubs.w", "out/bootstrap-lib/fiber_stubs.o", "-O0", ""))
    out = out.add_target(with_object_target("bootstrap-channel-runtime-object", "seed", "rt/channel_runtime.w", "out/bootstrap-lib/channel_runtime.o", "-O0", ""))
    out = out.add_target(with_object_target("bootstrap-fiber-runtime-object", "seed", "rt/fiber_runtime.w", "out/bootstrap-lib/fiber_runtime.o", "-O0", ""))
    out = out.add_target(with_object_target("bootstrap-fiber-core-object", "seed", "rt/fiber_core_darwin.w", "out/bootstrap-lib/fiber.o", "-O0", ""))
    var bootstrap_fiber_asm = target_new(.CompileAsmObject, "bootstrap-fiber-asm-object", "runtime/fiber_asm_aarch64.s").output("out/bootstrap-lib/fiber_asm.o")
    out = out.add_target(bootstrap_fiber_asm)

    var bootstrap_embedded_objects = target_new(.EmbedObjectFiles, "bootstrap-embedded-objects-asm", "").output("out/bootstrap-lib/embedded_objects.s")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/cimport_stubs.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("cimport_stubs_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/compat_runtime.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("compat_runtime_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/panic_runtime.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("panic_runtime_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/regex_runtime.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("regex_runtime_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/fiber_stubs.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("fiber_stubs_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/channel_runtime.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("channel_runtime_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/fiber_runtime.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("fiber_runtime_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/fiber.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("fiber_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/fiber_asm.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("fiber_asm_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/rt_core.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("rt_core_o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.input("out/bootstrap-lib/rt_darwin_aarch64.o")
    bootstrap_embedded_objects = bootstrap_embedded_objects.arg("rt_darwin_aarch64_o")
    out = out.add_target(bootstrap_embedded_objects)
    var bootstrap_embedded_objects_obj = target_new(.CompileAsmObject, "bootstrap-embedded-objects-object", "out/bootstrap-lib/embedded_objects.s").output("out/bootstrap-lib/embedded_objects.o")
    bootstrap_embedded_objects_obj = bootstrap_embedded_objects_obj.dep("bootstrap-embedded-objects-asm")
    out = out.add_target(bootstrap_embedded_objects_obj)

    var bootstrap_runtime = target_new(.Group, "bootstrap-runtime", "")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-llvm-link-metadata")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-rt-core-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-rt-darwin-aarch64-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-cimport-stubs-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-compat-runtime-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-panic-runtime-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-regex-runtime-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-fiber-stubs-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-channel-runtime-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-fiber-runtime-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-fiber-core-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-fiber-asm-object")
    bootstrap_runtime = bootstrap_runtime.dep("bootstrap-embedded-objects-object")
    out = out.add_target(bootstrap_runtime)

    var llvm_bridge = target_new(.WithCompilerBuild, "llvm-bridge-object", "seed").output("out/lib/llvm_bridge.o")
    llvm_bridge = llvm_bridge.input("rt/llvm_bridge.w")
    llvm_bridge = llvm_bridge.arg("--emit-obj")
    llvm_bridge = llvm_bridge.arg("--no-prelude")
    llvm_bridge = llvm_bridge.arg("-O0")
    out = out.add_target(llvm_bridge)

    var clang_bridge = target_new(.WithCompilerBuild, "clang-bridge-object", "seed").output("out/lib/clang_bridge.o")
    clang_bridge = clang_bridge.input("rt/clang_bridge.w")
    clang_bridge = clang_bridge.arg("--emit-obj")
    clang_bridge = clang_bridge.arg("--no-prelude")
    clang_bridge = clang_bridge.arg("-O0")
    out = out.add_target(clang_bridge)

    var llvm_link_metadata = target_new(41 as BuildKind, "llvm-link-metadata", "").output("out/lib/.llvm-link-ready")
    llvm_link_metadata = llvm_link_metadata.input("out/lib/llvm_bridge.o")
    llvm_link_metadata = llvm_link_metadata.input("out/lib/clang_bridge.o")
    llvm_link_metadata = llvm_link_metadata.dep("llvm-bridge-object")
    llvm_link_metadata = llvm_link_metadata.dep("clang-bridge-object")
    out = out.add_target(llvm_link_metadata)

    var stage1 = target_new(.WithCompilerBuild, "stage1", "seed").output("out/bin/with-stage1")
    stage1 = stage1.input("out/gen/main.w")
    stage1 = stage1.arg("-O0")
    stage1 = stage1.dep("compiler-sources")
    stage1 = stage1.dep("compat-runtime-source")
    stage1 = stage1.dep("bootstrap-runtime")
    out = out.add_target(stage1)

    var stage2 = target_new(.WithCompilerBuild, "stage2", "out/bin/with-stage1").output("out/bin/with-stage2")
    stage2 = stage2.input("out/gen/main.w")
    stage2 = stage2.arg("-O0")
    stage2 = stage2.dep("stage1")
    stage2 = stage2.dep("compat-runtime-source")
    out = out.add_target(stage2)

    var stage3 = target_new(.WithCompilerBuild, "stage3", "out/bin/with-stage2").output("out/bin/with-stage3")
    stage3 = stage3.input("out/gen/main.w")
    stage3 = stage3.arg("-O0")
    stage3 = stage3.dep("stage2")
    stage3 = stage3.dep("compat-runtime-source")
    out = out.add_target(stage3)

    var stage2_fixpoint = target_new(.WithCompilerBuild, "stage2-fixpoint-object", "out/bin/with-stage1").output("out/bin/with-stage2-fixpoint.o")
    stage2_fixpoint = stage2_fixpoint.input("out/gen/main.w")
    stage2_fixpoint = stage2_fixpoint.arg("--emit-obj")
    stage2_fixpoint = stage2_fixpoint.arg("-O0")
    stage2_fixpoint = stage2_fixpoint.dep("stage1")
    stage2_fixpoint = stage2_fixpoint.dep("compat-runtime-source")
    out = out.add_target(stage2_fixpoint)

    var stage3_fixpoint = target_new(.WithCompilerBuild, "stage3-fixpoint-object", "out/bin/with-stage2").output("out/bin/with-stage3-fixpoint.o")
    stage3_fixpoint = stage3_fixpoint.input("out/gen/main.w")
    stage3_fixpoint = stage3_fixpoint.arg("--emit-obj")
    stage3_fixpoint = stage3_fixpoint.arg("-O0")
    stage3_fixpoint = stage3_fixpoint.dep("stage2")
    stage3_fixpoint = stage3_fixpoint.dep("compat-runtime-source")
    out = out.add_target(stage3_fixpoint)

    var selfcheck = target_new(.RunCorpusTest, "selfcheck", "out/bin/with-stage2")
    selfcheck = selfcheck.output("out/corpus/selfcheck")
    selfcheck = selfcheck.arg("check")
    selfcheck = selfcheck.arg("src/main.w")
    selfcheck = selfcheck.dep("stage2")
    out = out.add_target(selfcheck)

    var fixpoint = target_new(.FixpointCompare, "fixpoint", "out/bin/with-stage2-fixpoint.o")
    fixpoint = fixpoint.arg("out/bin/with-stage3-fixpoint.o")
    fixpoint = fixpoint.dep("stage2-fixpoint-object")
    fixpoint = fixpoint.dep("stage3-fixpoint-object")
    out = out.add_target(fixpoint)

    var verified = target_new(.Group, "verified-existing-stage", "")
    verified = verified.dep("selfcheck")
    verified = verified.dep("fixpoint")
    out = out.add_target(verified)

    var rt_core = target_new(.WithCompilerBuild, "rt-core-object", "out/bin/with-stage2").output("out/lib/rt_core.o")
    rt_core = rt_core.input("rt/rt_core.w")
    rt_core = rt_core.arg("--emit-obj")
    rt_core = rt_core.arg("--no-prelude")
    rt_core = rt_core.arg("-O2")
    rt_core = rt_core.dep("stage2")
    out = out.add_target(rt_core)

    var rt_darwin = target_new(.WithCompilerBuild, "rt-darwin-aarch64-object", "out/bin/with-stage2").output("out/lib/rt_darwin_aarch64.o")
    rt_darwin = rt_darwin.input("rt/darwin_aarch64.w")
    rt_darwin = rt_darwin.arg("--emit-obj")
    rt_darwin = rt_darwin.arg("--no-prelude")
    rt_darwin = rt_darwin.arg("-O2")
    rt_darwin = rt_darwin.dep("stage2")
    out = out.add_target(rt_darwin)

    var cimport_stubs = target_new(.WithCompilerBuild, "cimport-stubs-object", "out/bin/with-stage2").output("out/lib/cimport_stubs.o")
    cimport_stubs = cimport_stubs.input("rt/cimport_stubs.w")
    cimport_stubs = cimport_stubs.arg("--emit-obj")
    cimport_stubs = cimport_stubs.arg("--no-prelude")
    cimport_stubs = cimport_stubs.arg("-O0")
    cimport_stubs = cimport_stubs.dep("stage2")
    out = out.add_target(cimport_stubs)

    var compat_runtime_obj = target_new(.WithCompilerBuild, "compat-runtime-object", "out/bin/with-stage2").output("out/lib/compat_runtime.o")
    compat_runtime_obj = compat_runtime_obj.input("out/gen/compat_runtime.w")
    compat_runtime_obj = compat_runtime_obj.arg("--emit-obj")
    compat_runtime_obj = compat_runtime_obj.arg("--no-prelude")
    compat_runtime_obj = compat_runtime_obj.arg("-O0")
    compat_runtime_obj = compat_runtime_obj.dep("stage2")
    compat_runtime_obj = compat_runtime_obj.dep("compat-runtime-source")
    out = out.add_target(compat_runtime_obj)

    var panic_runtime = target_new(.WithCompilerBuild, "panic-runtime-object", "out/bin/with-stage2").output("out/lib/panic_runtime.o")
    panic_runtime = panic_runtime.input("rt/panic_runtime.w")
    panic_runtime = panic_runtime.arg("--emit-obj")
    panic_runtime = panic_runtime.arg("--no-prelude")
    panic_runtime = panic_runtime.arg("-O0")
    panic_runtime = panic_runtime.dep("stage2")
    out = out.add_target(panic_runtime)

    var regex_runtime_ir = target_new(34 as BuildKind, "regex-runtime-ir", "out/bin/with-stage2").output("out/tmp/regex_runtime.ll")
    regex_runtime_ir = regex_runtime_ir.input("rt/regex_runtime.w")
    regex_runtime_ir = regex_runtime_ir.arg("--no-prelude")
    regex_runtime_ir = regex_runtime_ir.dep("stage2")
    out = out.add_target(regex_runtime_ir)

    var regex_runtime = target_new(.CompileLlvmIrObject, "regex-runtime-object", "out/tmp/regex_runtime.ll").output("out/lib/regex_runtime.o")
    out = out.add_target(regex_runtime)

    var fiber_stubs = target_new(.WithCompilerBuild, "fiber-stubs-object", "out/bin/with-stage2").output("out/lib/fiber_stubs.o")
    fiber_stubs = fiber_stubs.input("rt/fiber_stubs.w")
    fiber_stubs = fiber_stubs.arg("--emit-obj")
    fiber_stubs = fiber_stubs.arg("--no-prelude")
    fiber_stubs = fiber_stubs.arg("-O0")
    fiber_stubs = fiber_stubs.dep("stage2")
    out = out.add_target(fiber_stubs)

    var channel_runtime = target_new(.WithCompilerBuild, "channel-runtime-object", "out/bin/with-stage2").output("out/lib/channel_runtime.o")
    channel_runtime = channel_runtime.input("rt/channel_runtime.w")
    channel_runtime = channel_runtime.arg("--emit-obj")
    channel_runtime = channel_runtime.arg("--no-prelude")
    channel_runtime = channel_runtime.arg("-O0")
    channel_runtime = channel_runtime.dep("stage2")
    out = out.add_target(channel_runtime)

    var fiber_runtime = target_new(.WithCompilerBuild, "fiber-runtime-object", "out/bin/with-stage2").output("out/lib/fiber_runtime.o")
    fiber_runtime = fiber_runtime.input("rt/fiber_runtime.w")
    fiber_runtime = fiber_runtime.arg("--emit-obj")
    fiber_runtime = fiber_runtime.arg("--no-prelude")
    fiber_runtime = fiber_runtime.arg("-O0")
    fiber_runtime = fiber_runtime.dep("stage2")
    out = out.add_target(fiber_runtime)

    var fiber_core = target_new(.WithCompilerBuild, "fiber-core-object", "out/bin/with-stage2").output("out/lib/fiber.o")
    fiber_core = fiber_core.input("rt/fiber_core_darwin.w")
    fiber_core = fiber_core.arg("--emit-obj")
    fiber_core = fiber_core.arg("--no-prelude")
    fiber_core = fiber_core.arg("-O0")
    fiber_core = fiber_core.dep("stage2")
    out = out.add_target(fiber_core)

    var fiber_asm = target_new(.CompileAsmObject, "fiber-asm-object", "runtime/fiber_asm_aarch64.s").output("out/lib/fiber_asm.o")
    out = out.add_target(fiber_asm)

    var embedded_objects = target_new(.EmbedObjectFiles, "embedded-objects-asm", "").output("out/lib/embedded_objects.s")
    embedded_objects = embedded_objects.input("out/lib/cimport_stubs.o")
    embedded_objects = embedded_objects.arg("cimport_stubs_o")
    embedded_objects = embedded_objects.input("out/lib/compat_runtime.o")
    embedded_objects = embedded_objects.arg("compat_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/panic_runtime.o")
    embedded_objects = embedded_objects.arg("panic_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/regex_runtime.o")
    embedded_objects = embedded_objects.arg("regex_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/fiber_stubs.o")
    embedded_objects = embedded_objects.arg("fiber_stubs_o")
    embedded_objects = embedded_objects.input("out/lib/channel_runtime.o")
    embedded_objects = embedded_objects.arg("channel_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/fiber_runtime.o")
    embedded_objects = embedded_objects.arg("fiber_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/fiber.o")
    embedded_objects = embedded_objects.arg("fiber_o")
    embedded_objects = embedded_objects.input("out/lib/fiber_asm.o")
    embedded_objects = embedded_objects.arg("fiber_asm_o")
    embedded_objects = embedded_objects.input("out/lib/rt_core.o")
    embedded_objects = embedded_objects.arg("rt_core_o")
    embedded_objects = embedded_objects.input("out/lib/rt_darwin_aarch64.o")
    embedded_objects = embedded_objects.arg("rt_darwin_aarch64_o")
    out = out.add_target(embedded_objects)

    var embedded_objects_obj = target_new(.CompileAsmObject, "embedded-objects-object", "out/lib/embedded_objects.s").output("out/lib/embedded_objects.o")
    out = out.add_target(embedded_objects_obj)

    var runtime = target_new(.Group, "runtime", "")
    runtime = runtime.dep("embedded-objects-object")
    out = out.add_target(runtime)

    var compiler = target_new(.WithCompilerBuild, "build", "out/bin/with-stage2").output("out/bin/with")
    compiler = compiler.input("out/gen/main.w")
    compiler = compiler.arg("-O0")
    compiler = compiler.dep("llvm-link-metadata")
    compiler = compiler.dep("embedded-objects-object")
    out = out.add_target(compiler)

    var behavior_tests = target_new(.Test, "behavior-tests", "test/behavior/*.w")
    behavior_tests = behavior_tests.arg("compiler=out/bin/with-stage2")
    behavior_tests = behavior_tests.dep("selfcheck")
    out = out.add_target(behavior_tests)

    var native_compile_error_tests = target_new(.Test, "native-compile-error-tests", "test/compile_errors/*.w")
    native_compile_error_tests = native_compile_error_tests.dep("selfcheck")
    out = out.add_target(native_compile_error_tests)

    var native_codegen_tests = target_new(.Test, "native-codegen-tests", "test/codegen/*.w")
    native_codegen_tests = native_codegen_tests.dep("selfcheck")
    out = out.add_target(native_codegen_tests)

    var native_spec_tests = target_new(.Test, "native-spec-tests", "test/spec/*.w")
    native_spec_tests = native_spec_tests.dep("selfcheck")
    out = out.add_target(native_spec_tests)

    var native_phase_tests = target_new(.Test, "native-phase-tests", "test/phase/*.w")
    native_phase_tests = native_phase_tests.dep("selfcheck")
    out = out.add_target(native_phase_tests)

    var cli_selfhost_smoke_tests = target_new(40 as BuildKind, "cli-selfhost-smoke-tests", "out/bin/with-stage2")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.arg("smoke")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.input("out/bin/with-stage2")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_smoke_tests)

    var cli_selfhost_one_liner_tests = target_new(40 as BuildKind, "cli-selfhost-one-liner-tests", "out/bin/with-stage2")
    cli_selfhost_one_liner_tests = cli_selfhost_one_liner_tests.arg("one-liner")
    cli_selfhost_one_liner_tests = cli_selfhost_one_liner_tests.input("out/bin/with-stage2")
    cli_selfhost_one_liner_tests = cli_selfhost_one_liner_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_one_liner_tests)

    var cli_selfhost_object_symbol_tests = target_new(40 as BuildKind, "cli-selfhost-object-symbol-tests", "out/bin/with-stage2")
    cli_selfhost_object_symbol_tests = cli_selfhost_object_symbol_tests.arg("object-symbol")
    cli_selfhost_object_symbol_tests = cli_selfhost_object_symbol_tests.input("out/bin/with-stage2")
    cli_selfhost_object_symbol_tests = cli_selfhost_object_symbol_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_object_symbol_tests)

    var cli_selfhost_build_w_tests = target_new(40 as BuildKind, "cli-selfhost-build-w-tests", "out/bin/with-stage2")
    cli_selfhost_build_w_tests = cli_selfhost_build_w_tests.arg("build-w")
    cli_selfhost_build_w_tests = cli_selfhost_build_w_tests.input("out/bin/with-stage2")
    cli_selfhost_build_w_tests = cli_selfhost_build_w_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_build_w_tests)

    var cli_selfhost_project_tests = target_new(40 as BuildKind, "cli-selfhost-project-tests", "out/bin/with-stage2")
    cli_selfhost_project_tests = cli_selfhost_project_tests.arg("project")
    cli_selfhost_project_tests = cli_selfhost_project_tests.input("out/bin/with-stage2")
    cli_selfhost_project_tests = cli_selfhost_project_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_project_tests)

    var cli_selfhost_edge_tests = target_new(40 as BuildKind, "cli-selfhost-edge-tests", "out/bin/with-stage2")
    cli_selfhost_edge_tests = cli_selfhost_edge_tests.arg("edge")
    cli_selfhost_edge_tests = cli_selfhost_edge_tests.input("out/bin/with-stage2")
    cli_selfhost_edge_tests = cli_selfhost_edge_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_edge_tests)

    var cli_selfhost_parallel_tests = target_new(40 as BuildKind, "cli-selfhost-parallel-tests", "out/bin/with-stage2")
    cli_selfhost_parallel_tests = cli_selfhost_parallel_tests.arg("test-parallel")
    cli_selfhost_parallel_tests = cli_selfhost_parallel_tests.input("out/bin/with-stage2")
    cli_selfhost_parallel_tests = cli_selfhost_parallel_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_parallel_tests)

    var c_migrator_pcre2_prep_tests = target_new(40 as BuildKind, "c-migrator-pcre2-prep-tests", "out/bin/with-stage2")
    c_migrator_pcre2_prep_tests = c_migrator_pcre2_prep_tests.arg("pcre2-prep")
    c_migrator_pcre2_prep_tests = c_migrator_pcre2_prep_tests.input("out/bin/with-stage2")
    c_migrator_pcre2_prep_tests = c_migrator_pcre2_prep_tests.dep("selfcheck")
    out = out.add_target(c_migrator_pcre2_prep_tests)

    var c_migrator_basic_tests = target_new(40 as BuildKind, "c-migrator-basic-tests", "out/bin/with-stage2")
    c_migrator_basic_tests = c_migrator_basic_tests.arg("migrate-basic")
    c_migrator_basic_tests = c_migrator_basic_tests.input("out/bin/with-stage2")
    c_migrator_basic_tests = c_migrator_basic_tests.dep("selfcheck")
    out = out.add_target(c_migrator_basic_tests)

    var c_migrator_core_tests = target_new(40 as BuildKind, "c-migrator-core-tests", "out/bin/with-stage2")
    c_migrator_core_tests = c_migrator_core_tests.arg("migrate-core")
    c_migrator_core_tests = c_migrator_core_tests.input("out/bin/with-stage2")
    c_migrator_core_tests = c_migrator_core_tests.dep("selfcheck")
    out = out.add_target(c_migrator_core_tests)

    var c_migrator_tests = target_new(.Group, "c-migrator-tests", "")
    c_migrator_tests = c_migrator_tests.dep("c-migrator-basic-tests")
    c_migrator_tests = c_migrator_tests.dep("c-migrator-core-tests")
    c_migrator_tests = c_migrator_tests.dep("c-migrator-pcre2-prep-tests")
    out = out.add_target(c_migrator_tests)

    var issue61_regression = target_new(.SelfhostNoopLocalRegression, "issue61-regression", "out/bin/with-stage2")
    issue61_regression = issue61_regression.input("out/bin/with-stage2")
    issue61_regression = issue61_regression.dep("selfcheck")
    out = out.add_target(issue61_regression)

    var embedded_runtime_regression = target_new(.EmbeddedRuntimeExtractTest, "embedded-runtime-regression", "out/bin/with")
    embedded_runtime_regression = embedded_runtime_regression.input("out/bin/with")
    embedded_runtime_regression = embedded_runtime_regression.dep("build")
    out = out.add_target(embedded_runtime_regression)

    var tests = target_new(.Group, "test", "")
    tests = tests.dep("behavior-tests")
    tests = tests.dep("native-compile-error-tests")
    tests = tests.dep("native-codegen-tests")
    tests = tests.dep("native-spec-tests")
    tests = tests.dep("native-phase-tests")
    tests = tests.dep("cli-selfhost-smoke-tests")
    tests = tests.dep("cli-selfhost-one-liner-tests")
    tests = tests.dep("cli-selfhost-object-symbol-tests")
    tests = tests.dep("cli-selfhost-build-w-tests")
    tests = tests.dep("cli-selfhost-project-tests")
    tests = tests.dep("cli-selfhost-edge-tests")
    tests = tests.dep("cli-selfhost-parallel-tests")
    tests = tests.dep("issue61-regression")
    tests = tests.dep("embedded-runtime-regression")
    out = out.add_target(tests)

    var install_user = target_new(.Install, "install-user", "out/bin/with").output("$HOME/.local/bin/with")
    install_user = install_user.input("out/bin/with")
    install_user = install_user.arg("0755")
    install_user = install_user.dep("build")
    out = out.add_target(install_user)

    out = out.add_target(install_file_target("install-compiler", "out/bin/with-stage2", "$INSTALL_BINDIR/with", "0755", "stage2"))
    out = out.add_target(install_file_target("install-rt-core", "out/lib/rt_core.o", "$INSTALL_LIBDIR/rt_core.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-rt-darwin-aarch64", "out/lib/rt_darwin_aarch64.o", "$INSTALL_LIBDIR/rt_darwin_aarch64.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-cimport-stubs", "out/lib/cimport_stubs.o", "$INSTALL_LIBDIR/cimport_stubs.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-compat-runtime", "out/lib/compat_runtime.o", "$INSTALL_LIBDIR/compat_runtime.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-panic-runtime", "out/lib/panic_runtime.o", "$INSTALL_LIBDIR/panic_runtime.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-regex-runtime", "out/lib/regex_runtime.o", "$INSTALL_LIBDIR/regex_runtime.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-fiber-stubs", "out/lib/fiber_stubs.o", "$INSTALL_LIBDIR/fiber_stubs.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-channel-runtime", "out/lib/channel_runtime.o", "$INSTALL_LIBDIR/channel_runtime.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-fiber-runtime", "out/lib/fiber_runtime.o", "$INSTALL_LIBDIR/fiber_runtime.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-fiber-core", "out/lib/fiber.o", "$INSTALL_LIBDIR/fiber.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-fiber-asm", "out/lib/fiber_asm.o", "$INSTALL_LIBDIR/fiber_asm.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-embedded-objects", "out/lib/embedded_objects.o", "$INSTALL_LIBDIR/embedded_objects.o", "0644", "runtime"))
    out = out.add_target(install_file_target("install-embedded-objects-asm", "out/lib/embedded_objects.s", "$INSTALL_LIBDIR/embedded_objects.s", "0644", "runtime"))
    out = out.add_target(install_file_target("install-llvm-bridge", "out/lib/llvm_bridge.o", "$INSTALL_LIBDIR/llvm_bridge.o", "0644", "llvm-link-metadata"))
    out = out.add_target(install_file_target("install-clang-bridge", "out/lib/clang_bridge.o", "$INSTALL_LIBDIR/clang_bridge.o", "0644", "llvm-link-metadata"))
    out = out.add_target(install_file_target("install-llvm-link-rsp", "out/lib/llvm_link.rsp", "$INSTALL_LIBDIR/llvm_link.rsp", "0644", "llvm-link-metadata"))
    out = out.add_target(install_file_target("install-llvm-cc", "out/lib/llvm_cc", "$INSTALL_LIBDIR/llvm_cc", "0644", "llvm-link-metadata"))
    var install = target_new(.Group, "install", "")
    install = install.dep("install-compiler")
    install = install.dep("install-rt-core")
    install = install.dep("install-rt-darwin-aarch64")
    install = install.dep("install-cimport-stubs")
    install = install.dep("install-compat-runtime")
    install = install.dep("install-panic-runtime")
    install = install.dep("install-regex-runtime")
    install = install.dep("install-fiber-stubs")
    install = install.dep("install-channel-runtime")
    install = install.dep("install-fiber-runtime")
    install = install.dep("install-fiber-core")
    install = install.dep("install-fiber-asm")
    install = install.dep("install-embedded-objects")
    install = install.dep("install-embedded-objects-asm")
    install = install.dep("install-llvm-bridge")
    install = install.dep("install-clang-bridge")
    install = install.dep("install-llvm-link-rsp")
    install = install.dep("install-llvm-cc")
    out = out.add_target(install)

    var update_seed = target_new(.Install, "update-seed", "out/bin/with-stage2").output("src/main")
    update_seed = update_seed.input("out/bin/with-stage2")
    update_seed = update_seed.arg("0755")
    update_seed = update_seed.dep("verified-existing-stage")
    out = out.add_target(update_seed)

    var clean = target_new(.Clean, "clean", "")
    clean = clean.arg("out")
    clean = clean.arg(".with")
    clean = clean.arg("src/main.c")
    clean = clean.arg("src/main.o")
    clean = clean.arg("src/bootstrap_main.c")
    clean = clean.arg("src/bootstrap_main.o")
    clean = clean.arg("src/main_emit_temp.c")
    clean = clean.arg("src/main_emit_temp.o")
    clean = clean.arg("main.c")
    clean = clean.arg("main.o")
    clean = clean.arg("bootstrap_main.c")
    clean = clean.arg("bootstrap_main.o")
    clean = clean.arg("main_emit_temp.c")
    clean = clean.arg("main_emit_temp.o")
    out = out.add_target(clean)

    var pcre2_reference = target_new(42 as BuildKind, "pcre2-reference", "pcre2-10.47").output("out/pcre2_reference/pcre2-10.47/.with-reference-ready")
    pcre2_reference = pcre2_reference.arg("https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.gz")
    out = out.add_target(pcre2_reference)

    var pcre2_migrate = target_new(43 as BuildKind, "pcre2-migrate", "out/bin/with").output("out/gen/.regex-migrate-stamp")
    pcre2_migrate = pcre2_migrate.input("out/pcre2_reference/pcre2-10.47/src")
    pcre2_migrate = pcre2_migrate.arg("out/pcre2_migrated")
    pcre2_migrate = pcre2_migrate.arg("pcre2demo.c")
    pcre2_migrate = pcre2_migrate.arg("pcre2grep.c")
    pcre2_migrate = pcre2_migrate.arg("pcre2posix_test.c")
    pcre2_migrate = pcre2_migrate.arg("pcre2_jit_test.c")
    pcre2_migrate = pcre2_migrate.arg("pcre2_dftables.c")
    pcre2_migrate = pcre2_migrate.arg("pcre2_fuzzsupport.c")
    pcre2_migrate = pcre2_migrate.dep("pcre2-reference")
    out = out.add_target(pcre2_migrate)

    var pcre2_build = target_new(29 as BuildKind, "pcre2-build", "out/bin/with").output("out/pcre2_build")
    pcre2_build = pcre2_build.input("out/pcre2_migrated")
    pcre2_build = pcre2_build.dep("build")
    out = out.add_target(pcre2_build)

    var pcre2_test = target_new(.Pcre2RunTest, "pcre2-test", "out/pcre2_build/bin/pcre2test")
    pcre2_test = pcre2_test.input("out/pcre2_migrated")
    pcre2_test = pcre2_test.input("out/pcre2_build/bin/pcre2test")
    pcre2_test = pcre2_test.input("out/pcre2_reference/pcre2-10.47/RunTest")
    pcre2_test = pcre2_test.arg("out/pcre2_reference/pcre2-10.47")
    pcre2_test = pcre2_test.dep("verified-existing-stage")
    out = out.add_target(pcre2_test)

    var pcre2_check_generated = target_new(27 as BuildKind, "pcre2-check-generated", "out/bin/with")
    pcre2_check_generated = pcre2_check_generated.input("out/pcre2_build/lib/std/re")
    pcre2_check_generated = pcre2_check_generated.dep("build")
    out = out.add_target(pcre2_check_generated)

    var pcre2_promote = target_new(28 as BuildKind, "pcre2-promote", "out/bin/with").output("lib/std/re")
    pcre2_promote = pcre2_promote.input("out/pcre2_build/lib/std/re")
    pcre2_promote = pcre2_promote.dep("pcre2-test")
    out = out.add_target(pcre2_promote)

    out.default("verified-existing-stage")
