use std.build

pub fn build(b: Build) -> Build:
    var out = b

    var compiler_sources = target_new(.GenerateCompilerEntrypoints, "compiler-sources", "").output("out/gen/.generated-stamp")
    compiler_sources = compiler_sources.input("src/main.w")
    compiler_sources = compiler_sources.input("src/bootstrap_main.w")
    compiler_sources = compiler_sources.input("src/main_emit_temp.w")
    compiler_sources = compiler_sources.input("src/version")
    out = out.add_target(compiler_sources)

    var compat_runtime = target_new(33 as BuildKind, "compat-runtime-source", "rt/compat_runtime.w").output("out/gen/compat_runtime.w")
    out = out.add_target(compat_runtime)

    var stage1 = target_new(.WithCompilerBuild, "stage1", "seed").output("out/bin/with-stage1")
    stage1 = stage1.input("out/gen/main.w")
    stage1 = stage1.arg("-O0")
    stage1 = stage1.dep("compiler-sources")
    stage1 = stage1.dep("compat-runtime-source")
    out = out.add_target(stage1)

    var stage2 = target_new(.WithCompilerBuild, "stage2", "out/bin/with-stage1").output("out/bin/with-stage2")
    stage2 = stage2.input("out/gen/main.w")
    stage2 = stage2.arg("-O0")
    stage2 = stage2.dep("stage1")
    stage2 = stage2.dep("compat-runtime-source")
    out = out.add_target(stage2)

    var stage3 = target_new(.WithCompilerBuild, "stage3", "out/bin/with-stage2").output("out/bin/with-stage3")
    stage3 = stage3.input("out/gen/main.w")
    stage3 = stage3.arg("-O0")
    stage3 = stage3.dep("stage2")
    stage3 = stage3.dep("compat-runtime-source")
    out = out.add_target(stage3)

    var stage2_fixpoint = target_new(.WithCompilerBuild, "stage2-fixpoint-object", "out/bin/with-stage1").output("out/bin/with-stage2-fixpoint.o")
    stage2_fixpoint = stage2_fixpoint.input("out/gen/main.w")
    stage2_fixpoint = stage2_fixpoint.arg("--emit-obj")
    stage2_fixpoint = stage2_fixpoint.arg("-O0")
    stage2_fixpoint = stage2_fixpoint.dep("stage1")
    stage2_fixpoint = stage2_fixpoint.dep("compat-runtime-source")
    out = out.add_target(stage2_fixpoint)

    var stage3_fixpoint = target_new(.WithCompilerBuild, "stage3-fixpoint-object", "out/bin/with-stage2").output("out/bin/with-stage3-fixpoint.o")
    stage3_fixpoint = stage3_fixpoint.input("out/gen/main.w")
    stage3_fixpoint = stage3_fixpoint.arg("--emit-obj")
    stage3_fixpoint = stage3_fixpoint.arg("-O0")
    stage3_fixpoint = stage3_fixpoint.dep("stage2")
    stage3_fixpoint = stage3_fixpoint.dep("compat-runtime-source")
    out = out.add_target(stage3_fixpoint)

    var selfcheck = target_new(.RunCorpusTest, "selfcheck", "out/bin/with-stage2")
    selfcheck = selfcheck.output("out/corpus/selfcheck")
    selfcheck = selfcheck.arg("check")
    selfcheck = selfcheck.arg("src/main.w")
    selfcheck = selfcheck.dep("stage2")
    out = out.add_target(selfcheck)

    var fixpoint = target_new(.FixpointCompare, "fixpoint", "out/bin/with-stage2-fixpoint.o")
    fixpoint = fixpoint.arg("out/bin/with-stage3-fixpoint.o")
    fixpoint = fixpoint.dep("stage2-fixpoint-object")
    fixpoint = fixpoint.dep("stage3-fixpoint-object")
    out = out.add_target(fixpoint)

    var verified = target_new(.Group, "verified-existing-stage", "")
    verified = verified.dep("selfcheck")
    verified = verified.dep("fixpoint")
    out = out.add_target(verified)

    var rt_core = target_new(.WithCompilerBuild, "rt-core-object", "out/bin/with-stage2").output("out/lib/rt_core.o")
    rt_core = rt_core.input("rt/rt_core.w")
    rt_core = rt_core.arg("--emit-obj")
    rt_core = rt_core.arg("--no-prelude")
    rt_core = rt_core.arg("-O2")
    rt_core = rt_core.dep("stage2")
    out = out.add_target(rt_core)

    var rt_darwin = target_new(.WithCompilerBuild, "rt-darwin-aarch64-object", "out/bin/with-stage2").output("out/lib/rt_darwin_aarch64.o")
    rt_darwin = rt_darwin.input("rt/darwin_aarch64.w")
    rt_darwin = rt_darwin.arg("--emit-obj")
    rt_darwin = rt_darwin.arg("--no-prelude")
    rt_darwin = rt_darwin.arg("-O2")
    rt_darwin = rt_darwin.dep("stage2")
    out = out.add_target(rt_darwin)

    var cimport_stubs = target_new(.WithCompilerBuild, "cimport-stubs-object", "out/bin/with-stage2").output("out/lib/cimport_stubs.o")
    cimport_stubs = cimport_stubs.input("rt/cimport_stubs.w")
    cimport_stubs = cimport_stubs.arg("--emit-obj")
    cimport_stubs = cimport_stubs.arg("--no-prelude")
    cimport_stubs = cimport_stubs.arg("-O0")
    cimport_stubs = cimport_stubs.dep("stage2")
    out = out.add_target(cimport_stubs)

    var compat_runtime_obj = target_new(.WithCompilerBuild, "compat-runtime-object", "out/bin/with-stage2").output("out/lib/compat_runtime.o")
    compat_runtime_obj = compat_runtime_obj.input("out/gen/compat_runtime.w")
    compat_runtime_obj = compat_runtime_obj.arg("--emit-obj")
    compat_runtime_obj = compat_runtime_obj.arg("--no-prelude")
    compat_runtime_obj = compat_runtime_obj.arg("-O0")
    compat_runtime_obj = compat_runtime_obj.dep("stage2")
    compat_runtime_obj = compat_runtime_obj.dep("compat-runtime-source")
    out = out.add_target(compat_runtime_obj)

    var panic_runtime = target_new(.WithCompilerBuild, "panic-runtime-object", "out/bin/with-stage2").output("out/lib/panic_runtime.o")
    panic_runtime = panic_runtime.input("rt/panic_runtime.w")
    panic_runtime = panic_runtime.arg("--emit-obj")
    panic_runtime = panic_runtime.arg("--no-prelude")
    panic_runtime = panic_runtime.arg("-O0")
    panic_runtime = panic_runtime.dep("stage2")
    out = out.add_target(panic_runtime)

    var regex_runtime_ir = target_new(34 as BuildKind, "regex-runtime-ir", "out/bin/with-stage2").output("out/tmp/regex_runtime.ll")
    regex_runtime_ir = regex_runtime_ir.input("rt/regex_runtime.w")
    regex_runtime_ir = regex_runtime_ir.arg("--no-prelude")
    regex_runtime_ir = regex_runtime_ir.dep("stage2")
    out = out.add_target(regex_runtime_ir)

    var regex_runtime = target_new(.CompileLlvmIrObject, "regex-runtime-object", "out/tmp/regex_runtime.ll").output("out/lib/regex_runtime.o")
    out = out.add_target(regex_runtime)

    var fiber_stubs = target_new(.WithCompilerBuild, "fiber-stubs-object", "out/bin/with-stage2").output("out/lib/fiber_stubs.o")
    fiber_stubs = fiber_stubs.input("rt/fiber_stubs.w")
    fiber_stubs = fiber_stubs.arg("--emit-obj")
    fiber_stubs = fiber_stubs.arg("--no-prelude")
    fiber_stubs = fiber_stubs.arg("-O0")
    fiber_stubs = fiber_stubs.dep("stage2")
    out = out.add_target(fiber_stubs)

    var channel_runtime = target_new(.WithCompilerBuild, "channel-runtime-object", "out/bin/with-stage2").output("out/lib/channel_runtime.o")
    channel_runtime = channel_runtime.input("rt/channel_runtime.w")
    channel_runtime = channel_runtime.arg("--emit-obj")
    channel_runtime = channel_runtime.arg("--no-prelude")
    channel_runtime = channel_runtime.arg("-O0")
    channel_runtime = channel_runtime.dep("stage2")
    out = out.add_target(channel_runtime)

    var fiber_runtime = target_new(.WithCompilerBuild, "fiber-runtime-object", "out/bin/with-stage2").output("out/lib/fiber_runtime.o")
    fiber_runtime = fiber_runtime.input("rt/fiber_runtime.w")
    fiber_runtime = fiber_runtime.arg("--emit-obj")
    fiber_runtime = fiber_runtime.arg("--no-prelude")
    fiber_runtime = fiber_runtime.arg("-O0")
    fiber_runtime = fiber_runtime.dep("stage2")
    out = out.add_target(fiber_runtime)

    var fiber_core = target_new(.WithCompilerBuild, "fiber-core-object", "out/bin/with-stage2").output("out/lib/fiber.o")
    fiber_core = fiber_core.input("rt/fiber_core_darwin.w")
    fiber_core = fiber_core.arg("--emit-obj")
    fiber_core = fiber_core.arg("--no-prelude")
    fiber_core = fiber_core.arg("-O0")
    fiber_core = fiber_core.dep("stage2")
    out = out.add_target(fiber_core)

    var fiber_asm = target_new(.CompileAsmObject, "fiber-asm-object", "runtime/fiber_asm_aarch64.s").output("out/lib/fiber_asm.o")
    out = out.add_target(fiber_asm)

    var embedded_objects = target_new(.EmbedObjectFiles, "embedded-objects-asm", "").output("out/lib/embedded_objects.s")
    embedded_objects = embedded_objects.input("out/lib/cimport_stubs.o")
    embedded_objects = embedded_objects.arg("cimport_stubs_o")
    embedded_objects = embedded_objects.input("out/lib/compat_runtime.o")
    embedded_objects = embedded_objects.arg("compat_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/panic_runtime.o")
    embedded_objects = embedded_objects.arg("panic_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/regex_runtime.o")
    embedded_objects = embedded_objects.arg("regex_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/fiber_stubs.o")
    embedded_objects = embedded_objects.arg("fiber_stubs_o")
    embedded_objects = embedded_objects.input("out/lib/channel_runtime.o")
    embedded_objects = embedded_objects.arg("channel_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/fiber_runtime.o")
    embedded_objects = embedded_objects.arg("fiber_runtime_o")
    embedded_objects = embedded_objects.input("out/lib/fiber.o")
    embedded_objects = embedded_objects.arg("fiber_o")
    embedded_objects = embedded_objects.input("out/lib/fiber_asm.o")
    embedded_objects = embedded_objects.arg("fiber_asm_o")
    embedded_objects = embedded_objects.input("out/lib/rt_core.o")
    embedded_objects = embedded_objects.arg("rt_core_o")
    embedded_objects = embedded_objects.input("out/lib/rt_darwin_aarch64.o")
    embedded_objects = embedded_objects.arg("rt_darwin_aarch64_o")
    out = out.add_target(embedded_objects)

    var embedded_objects_obj = target_new(.CompileAsmObject, "embedded-objects-object", "out/lib/embedded_objects.s").output("out/lib/embedded_objects.o")
    out = out.add_target(embedded_objects_obj)

    var runtime = target_new(.Group, "runtime", "")
    runtime = runtime.dep("embedded-objects-object")
    out = out.add_target(runtime)

    var compiler = target_new(.WithCompilerBuild, "build", "out/bin/with-stage2").output("out/bin/with")
    compiler = compiler.input("out/gen/main.w")
    compiler = compiler.arg("-O0")
    compiler = compiler.dep("embedded-objects-object")
    out = out.add_target(compiler)

    var behavior_tests = target_new(.Test, "behavior-tests", "test/behavior/*.w")
    behavior_tests = behavior_tests.arg("compiler=out/bin/with-stage2")
    behavior_tests = behavior_tests.dep("selfcheck")
    out = out.add_target(behavior_tests)

    var native_compile_error_tests = target_new(.Test, "native-compile-error-tests", "test/compile_errors/*.w")
    native_compile_error_tests = native_compile_error_tests.dep("selfcheck")
    out = out.add_target(native_compile_error_tests)

    var native_codegen_tests = target_new(.Test, "native-codegen-tests", "test/codegen/*.w")
    native_codegen_tests = native_codegen_tests.dep("selfcheck")
    out = out.add_target(native_codegen_tests)

    var native_spec_tests = target_new(.Test, "native-spec-tests", "test/spec/*.w")
    native_spec_tests = native_spec_tests.dep("selfcheck")
    out = out.add_target(native_spec_tests)

    var native_phase_tests = target_new(.Test, "native-phase-tests", "test/phase/*.w")
    native_phase_tests = native_phase_tests.dep("selfcheck")
    out = out.add_target(native_phase_tests)

    var legacy_cli_selfhost_tests = target_new(.Command, "legacy-cli-selfhost-tests", "/usr/bin/env")
    legacy_cli_selfhost_tests = legacy_cli_selfhost_tests.input("scripts/run_cli_selfhost_tests.sh")
    legacy_cli_selfhost_tests = legacy_cli_selfhost_tests.input("out/bin/with-stage2")
    legacy_cli_selfhost_tests = legacy_cli_selfhost_tests.arg("WITH=out/bin/with-stage2")
    legacy_cli_selfhost_tests = legacy_cli_selfhost_tests.arg("scripts/run_cli_selfhost_tests.sh")
    legacy_cli_selfhost_tests = legacy_cli_selfhost_tests.dep("selfcheck")
    out = out.add_target(legacy_cli_selfhost_tests)

    var cli_selfhost_smoke_tests = target_new(40 as BuildKind, "cli-selfhost-smoke-tests", "out/bin/with-stage2")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.arg("smoke")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.input("out/bin/with-stage2")
    cli_selfhost_smoke_tests = cli_selfhost_smoke_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_smoke_tests)

    var cli_selfhost_one_liner_tests = target_new(40 as BuildKind, "cli-selfhost-one-liner-tests", "out/bin/with-stage2")
    cli_selfhost_one_liner_tests = cli_selfhost_one_liner_tests.arg("one-liner")
    cli_selfhost_one_liner_tests = cli_selfhost_one_liner_tests.input("out/bin/with-stage2")
    cli_selfhost_one_liner_tests = cli_selfhost_one_liner_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_one_liner_tests)

    var cli_selfhost_object_symbol_tests = target_new(40 as BuildKind, "cli-selfhost-object-symbol-tests", "out/bin/with-stage2")
    cli_selfhost_object_symbol_tests = cli_selfhost_object_symbol_tests.arg("object-symbol")
    cli_selfhost_object_symbol_tests = cli_selfhost_object_symbol_tests.input("out/bin/with-stage2")
    cli_selfhost_object_symbol_tests = cli_selfhost_object_symbol_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_object_symbol_tests)

    var cli_selfhost_build_w_tests = target_new(40 as BuildKind, "cli-selfhost-build-w-tests", "out/bin/with-stage2")
    cli_selfhost_build_w_tests = cli_selfhost_build_w_tests.arg("build-w")
    cli_selfhost_build_w_tests = cli_selfhost_build_w_tests.input("out/bin/with-stage2")
    cli_selfhost_build_w_tests = cli_selfhost_build_w_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_build_w_tests)

    var cli_selfhost_project_tests = target_new(40 as BuildKind, "cli-selfhost-project-tests", "out/bin/with-stage2")
    cli_selfhost_project_tests = cli_selfhost_project_tests.arg("project")
    cli_selfhost_project_tests = cli_selfhost_project_tests.input("out/bin/with-stage2")
    cli_selfhost_project_tests = cli_selfhost_project_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_project_tests)

    var cli_selfhost_edge_tests = target_new(40 as BuildKind, "cli-selfhost-edge-tests", "out/bin/with-stage2")
    cli_selfhost_edge_tests = cli_selfhost_edge_tests.arg("edge")
    cli_selfhost_edge_tests = cli_selfhost_edge_tests.input("out/bin/with-stage2")
    cli_selfhost_edge_tests = cli_selfhost_edge_tests.dep("selfcheck")
    out = out.add_target(cli_selfhost_edge_tests)

    var c_migrator_pcre2_prep_tests = target_new(40 as BuildKind, "c-migrator-pcre2-prep-tests", "out/bin/with-stage2")
    c_migrator_pcre2_prep_tests = c_migrator_pcre2_prep_tests.arg("pcre2-prep")
    c_migrator_pcre2_prep_tests = c_migrator_pcre2_prep_tests.input("out/bin/with-stage2")
    c_migrator_pcre2_prep_tests = c_migrator_pcre2_prep_tests.dep("selfcheck")
    out = out.add_target(c_migrator_pcre2_prep_tests)

    var c_migrator_basic_tests = target_new(40 as BuildKind, "c-migrator-basic-tests", "out/bin/with-stage2")
    c_migrator_basic_tests = c_migrator_basic_tests.arg("migrate-basic")
    c_migrator_basic_tests = c_migrator_basic_tests.input("out/bin/with-stage2")
    c_migrator_basic_tests = c_migrator_basic_tests.dep("selfcheck")
    out = out.add_target(c_migrator_basic_tests)

    var c_migrator_core_tests = target_new(40 as BuildKind, "c-migrator-core-tests", "out/bin/with-stage2")
    c_migrator_core_tests = c_migrator_core_tests.arg("migrate-core")
    c_migrator_core_tests = c_migrator_core_tests.input("out/bin/with-stage2")
    c_migrator_core_tests = c_migrator_core_tests.dep("selfcheck")
    out = out.add_target(c_migrator_core_tests)

    var c_migrator_tests = target_new(.Group, "c-migrator-tests", "")
    c_migrator_tests = c_migrator_tests.dep("c-migrator-basic-tests")
    c_migrator_tests = c_migrator_tests.dep("c-migrator-core-tests")
    c_migrator_tests = c_migrator_tests.dep("c-migrator-pcre2-prep-tests")
    out = out.add_target(c_migrator_tests)

    var issue61_regression = target_new(.SelfhostNoopLocalRegression, "issue61-regression", "out/bin/with-stage2")
    issue61_regression = issue61_regression.input("out/bin/with-stage2")
    issue61_regression = issue61_regression.dep("selfcheck")
    out = out.add_target(issue61_regression)

    var embedded_runtime_regression = target_new(.EmbeddedRuntimeExtractTest, "embedded-runtime-regression", "out/bin/with")
    embedded_runtime_regression = embedded_runtime_regression.input("out/bin/with")
    embedded_runtime_regression = embedded_runtime_regression.dep("build")
    out = out.add_target(embedded_runtime_regression)

    var tests = target_new(.Group, "test", "")
    tests = tests.dep("behavior-tests")
    tests = tests.dep("native-compile-error-tests")
    tests = tests.dep("native-codegen-tests")
    tests = tests.dep("native-spec-tests")
    tests = tests.dep("native-phase-tests")
    tests = tests.dep("cli-selfhost-smoke-tests")
    tests = tests.dep("cli-selfhost-one-liner-tests")
    tests = tests.dep("cli-selfhost-object-symbol-tests")
    tests = tests.dep("cli-selfhost-build-w-tests")
    tests = tests.dep("cli-selfhost-project-tests")
    tests = tests.dep("cli-selfhost-edge-tests")
    tests = tests.dep("issue61-regression")
    tests = tests.dep("embedded-runtime-regression")
    out = out.add_target(tests)

    var install_user = target_new(.Install, "install-user", "out/bin/with").output("$HOME/.local/bin/with")
    install_user = install_user.input("out/bin/with")
    install_user = install_user.arg("0755")
    install_user = install_user.dep("build")
    out = out.add_target(install_user)

    var update_seed = target_new(.Install, "update-seed", "out/bin/with-stage2").output("src/main")
    update_seed = update_seed.input("out/bin/with-stage2")
    update_seed = update_seed.arg("0755")
    update_seed = update_seed.dep("verified-existing-stage")
    out = out.add_target(update_seed)

    var pcre2_build = target_new(29 as BuildKind, "pcre2-build", "out/bin/with").output("out/pcre2_build")
    pcre2_build = pcre2_build.input("out/pcre2_migrated")
    pcre2_build = pcre2_build.dep("build")
    out = out.add_target(pcre2_build)

    var pcre2_test = target_new(.Pcre2RunTest, "pcre2-test", "out/pcre2_build/bin/pcre2test")
    pcre2_test = pcre2_test.input("out/pcre2_migrated")
    pcre2_test = pcre2_test.input("out/pcre2_build/bin/pcre2test")
    pcre2_test = pcre2_test.input("out/pcre2_reference/pcre2-10.47/RunTest")
    pcre2_test = pcre2_test.arg("out/pcre2_reference/pcre2-10.47")
    pcre2_test = pcre2_test.dep("verified-existing-stage")
    out = out.add_target(pcre2_test)

    var pcre2_check_generated = target_new(27 as BuildKind, "pcre2-check-generated", "out/bin/with")
    pcre2_check_generated = pcre2_check_generated.input("out/pcre2_build/lib/std/re")
    pcre2_check_generated = pcre2_check_generated.dep("build")
    out = out.add_target(pcre2_check_generated)

    var pcre2_promote = target_new(28 as BuildKind, "pcre2-promote", "out/bin/with").output("lib/std/re")
    pcre2_promote = pcre2_promote.input("out/pcre2_build/lib/std/re")
    pcre2_promote = pcre2_promote.dep("pcre2-test")
    out = out.add_target(pcre2_promote)

    out.default("verified-existing-stage")
