//! expect-stdout: ok

use Lexer
use Token

fn main:
    var lexer1 = Lexer.init("()[]{}:,.;\n", 0)
    let t1 = lexer1.tokenize()
    assert(t1.get_tag(0) == TokenKind.TK_L_PAREN())
    assert(t1.get_tag(1) == TokenKind.TK_R_PAREN())
    assert(t1.get_tag(2) == TokenKind.TK_L_BRACKET())
    assert(t1.get_tag(3) == TokenKind.TK_R_BRACKET())
    assert(t1.get_tag(4) == TokenKind.TK_L_BRACE())
    assert(t1.get_tag(5) == TokenKind.TK_R_BRACE())
    assert(t1.get_tag(6) == TokenKind.TK_COLON())
    assert(t1.get_tag(7) == TokenKind.TK_COMMA())
    assert(t1.get_tag(8) == TokenKind.TK_DOT())
    assert(t1.get_tag(9) == TokenKind.TK_SEMICOLON())
    assert(t1.get_tag(10) == TokenKind.TK_NEWLINE())
    assert(t1.get_tag(11) == TokenKind.TK_EOF())

    var lexer2 = Lexer.init("let x = 1\n    let y = 2\n", 0)
    let t2 = lexer2.tokenize()
    assert(t2.get_tag(0) == TokenKind.TK_KW_LET())
    assert(t2.get_tag(1) == TokenKind.TK_IDENT())
    assert(t2.get_tag(2) == TokenKind.TK_EQ())
    assert(t2.get_tag(3) == TokenKind.TK_INT_LIT())
    assert(t2.get_tag(4) == TokenKind.TK_NEWLINE())
    assert(t2.get_tag(5) == TokenKind.TK_KW_LET())
    assert(t2.get_tag(t2.len() - 1) == TokenKind.TK_EOF())

    var lexer3 = Lexer.init("name _tmp value2 .Red .Http500 .x", 0)
    let t3 = lexer3.tokenize()
    assert(t3.get_tag(0) == TokenKind.TK_IDENT())
    assert(t3.get_tag(1) == TokenKind.TK_IDENT())
    assert(t3.get_tag(2) == TokenKind.TK_IDENT())
    assert(t3.get_tag(3) == TokenKind.TK_DOT_IDENT())
    assert(t3.get_tag(4) == TokenKind.TK_DOT_IDENT())
    assert(t3.get_tag(5) == TokenKind.TK_DOT())
    assert(t3.get_tag(6) == TokenKind.TK_IDENT())
    assert(t3.get_tag(7) == TokenKind.TK_EOF())

    var lexer4 = Lexer.init("let x = 1 // keep\nlet y = 2 // eof", 0)
    let t4 = lexer4.tokenize()
    assert(t4.get_tag(0) == TokenKind.TK_KW_LET())
    assert(t4.get_tag(1) == TokenKind.TK_IDENT())
    assert(t4.get_tag(2) == TokenKind.TK_EQ())
    assert(t4.get_tag(3) == TokenKind.TK_INT_LIT())
    assert(t4.get_tag(4) == TokenKind.TK_NEWLINE())
    assert(t4.get_tag(5) == TokenKind.TK_KW_LET())
    assert(t4.get_tag(6) == TokenKind.TK_IDENT())
    assert(t4.get_tag(7) == TokenKind.TK_EQ())
    assert(t4.get_tag(8) == TokenKind.TK_INT_LIT())
    assert(t4.get_tag(9) == TokenKind.TK_EOF())

    println("ok")
