use std.fs
use std.process

fn main -> i32:
    let p = pid()
    print("pid=" ++ p.to_string() ++ " positive=" ++ (p > 0).to_string())
    let a = args()
    print("argc=" ++ a.len().to_string())
    print("argv0=[" ++ a.get(0) ++ "]")
    print("missing env len=" ++ env("WITH_AUDIT_NOPE_VAR").len().to_string())
    let s1 = set_env("WITH_AUDIT_PROBE_VAR", "probe-val-123")
    print("set_env rc=" ++ s1.to_string())
    print("get back=[" ++ env("WITH_AUDIT_PROBE_VAR") ++ "]")
    let s2 = set_env("WITH_AUDIT_PROBE_VAR", "")
    print("set empty rc=" ++ s2.to_string())
    print("get empty len=" ++ env("WITH_AUDIT_PROBE_VAR").len().to_string())
    print("empty vs unset same=" ++ (env("WITH_AUDIT_PROBE_VAR") == env("WITH_AUDIT_NOPE_VAR")).to_string())
    var ok_argv: Vec[str] = Vec.new()
    ok_argv.push("/bin/true")
    print("run true rc=" ++ run(&ok_argv).to_string())
    var fail_argv: Vec[str] = Vec.new()
    fail_argv.push("/bin/false")
    print("run false rc=" ++ run(&fail_argv).to_string())
    var code_argv: Vec[str] = Vec.new()
    code_argv.push("/bin/sh")
    code_argv.push("-c")
    code_argv.push("exit 42")
    print("run exit42 rc=" ++ run(&code_argv).to_string())
    var nope_argv: Vec[str] = Vec.new()
    nope_argv.push("/tmp/with_audit_NOPE_binary_xyz")
    print("run nonexistent rc=" ++ run(&nope_argv).to_string())
    let c = command("/bin/true")
    print("command run rc=" ++ c.run().to_string())
    print("command status rc=" ++ c.status().to_string())
    let c2 = command("/bin/sh").arg("-c").arg("exit 7")
    print("builder exit7 run=" ++ c2.run().to_string() ++ " status=" ++ c2.status().to_string())
    0
