// Test HashMap operations
fn main -> i32:
    var m: HashMap[str, i32] = HashMap.new()
    m.insert("a", 1)
    m.insert("b", 2)
    m.insert("c", 3)
    println(m.len())
    let v = m.get("b")
    println(v.unwrap())
    println(m.contains("a"))
    println(m.contains("z"))
    m.remove("b")
    println(m.len())
    let v2 = m.get("b")
    println(v2.is_none())
