/* Generated by with --emit-c (conservative MIR subset). */
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include "with_runtime.h"

void __with_main__1();
int64_t abs64__15(int64_t _1);
int64_t min64__21(int64_t _1, int64_t _2);
int64_t max64__22(int64_t _1, int64_t _2);
double sqrt_f64__26(double _1);
double pow_f64__29(double _1, double _2);
double floor_f64__33(double _1);
double ceil_f64__35(double _1);
double round_f64__37(double _1);
double sin_f64__39(double _1);
double cos_f64__41(double _1);
double tan_f64__43(double _1);
double log_f64__45(double _1);
double log10_f64__47(double _1);
double exp_f64__49(double _1);
double fabs_f64__50(double _1);
double fmod_f64__52(double _1, double _2);
double asin_f64__55(double _1);
double acos_f64__57(double _1);
double atan_f64__59(double _1);
double atan2_f64__61(double _1, double _2);
int64_t string_len__77(with_str _1);
int64_t view_len__79(const with_str* _1);
bool view_is_empty__82(const with_str* _1);
bool view_eq__84(const with_str* _1, const with_str* _2);
bool string_eq__85(with_str _1, with_str _2);
int32_t string_cmp__87(with_str _1, with_str _2);
bool is_alpha__89(int32_t _1);
bool is_digit__92(int32_t _1);
bool is_space__94(int32_t _1);
int64_t string_to_int__96(with_str _1);
int64_t lines__97(with_str _1);
int32_t parse__101(with_str _1);
int32_t sum__110(int64_t _1);
int64_t map__114(int64_t _1, int64_t _2);
int64_t filter__117(int64_t _1, int64_t _2);
bool contains__120(int64_t _1, int32_t _2);
bool file_exists__128(with_str _1);
int32_t remove_file__130(with_str _1);
int32_t rename_file__132(with_str _1, with_str _2);
int32_t create_dir__136(with_str _1);
int32_t remove_dir__141(with_str _1);
int32_t write_file__143(with_str _1, with_str _2);
with_str read_file__144(with_str _1);
void exit_code__160(int32_t _1);
int32_t system_cmd__161(with_str _1);
int32_t pid__162();
int64_t args__163();
with_str env__164(with_str _1);
int32_t set_env__166(with_str _1, with_str _2);
Command command__168(with_str _1);
int32_t Command_run__170(Command _1);
int32_t Command_status__173(Command _1);

void __with_main__1() {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _1 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    _1 = string_len__77(WITH_STR_LIT("Hello, World!"));
    goto bb1;
bb1:
    _0 = _1;
    return;
}

int64_t abs64__15(int64_t _1) {
    int64_t _0 __attribute__((unused)) = {0};
    bool _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = (_1 < 0);
    if (_2 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
    _4 = (0 - _1);
    _3 = _4;
    goto bb3;
bb2:
    _3 = _1;
    goto bb3;
bb3:
    _0 = _3;
    return _0;
}

int64_t min64__21(int64_t _1, int64_t _2) {
    int64_t _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = (_1 < _2);
    if (_3 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
    _4 = _1;
    goto bb3;
bb2:
    _4 = _2;
    goto bb3;
bb3:
    _0 = _4;
    return _0;
}

int64_t max64__22(int64_t _1, int64_t _2) {
    int64_t _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = (_1 > _2);
    if (_3 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
    _4 = _1;
    goto bb3;
bb2:
    _4 = _2;
    goto bb3;
bb3:
    _0 = _4;
    return _0;
}

double sqrt_f64__26(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double pow_f64__29(double _1, double _2) {
    double _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = min64__21(_1, _2);
    goto bb1;
bb1:
    _0 = _3;
    return _0;
}

double floor_f64__33(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double ceil_f64__35(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double round_f64__37(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double sin_f64__39(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double cos_f64__41(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double tan_f64__43(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double log_f64__45(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double log10_f64__47(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double exp_f64__49(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double fabs_f64__50(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double fmod_f64__52(double _1, double _2) {
    double _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = min64__21(_1, _2);
    goto bb1;
bb1:
    _0 = _3;
    return _0;
}

double asin_f64__55(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double acos_f64__57(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double atan_f64__59(double _1) {
    double _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

double atan2_f64__61(double _1, double _2) {
    double _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = min64__21(_1, _2);
    goto bb1;
bb1:
    _0 = _3;
    return _0;
}

int64_t string_len__77(with_str _1) {
    int64_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = string_len__77(_1);
    goto bb1;
bb1:
    _3 = ((int64_t)(_2));
    _0 = _3;
    return _0;
}

int64_t view_len__79(const with_str* _1) {
    int64_t _0 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _0 = _1.f81;
    return _0;
}

bool view_is_empty__82(const with_str* _1) {
    bool _0 __attribute__((unused)) = {0};
    bool _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = (_1.f81 == 0);
    _0 = _2;
    return _0;
}

bool view_eq__84(const with_str* _1, const with_str* _2) {
    bool _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = (_1 == _2);
    _0 = _3;
    return _0;
}

bool string_eq__85(with_str _1, with_str _2) {
    bool _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    bool _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = view_eq__84(_1, _2);
    goto bb1;
bb1:
    _4 = (_3 == 0);
    _0 = _4;
    return _0;
}

int32_t string_cmp__87(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = string_cmp__87(_1, _2);
    goto bb1;
bb1:
    _0 = _3;
    return _0;
}

bool is_alpha__89(int32_t _1) {
    bool _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _3 = (_2 != 0);
    _0 = _3;
    return _0;
}

bool is_digit__92(int32_t _1) {
    bool _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _3 = (_2 != 0);
    _0 = _3;
    return _0;
}

bool is_space__94(int32_t _1) {
    bool _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = abs64__15(_1);
    goto bb1;
bb1:
    _3 = (_2 != 0);
    _0 = _3;
    return _0;
}

int64_t string_to_int__96(with_str _1) {
    int64_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = with_parse_i64(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

int64_t lines__97(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    const int64_t* _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _2 = 0;
    _3 = (&_2);
    with_lines_out(_3, _1);
    goto bb1;
bb1:
    _0 = _2;
    return;
}

int32_t parse__101(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = string_to_int__96(_1);
    goto bb1;
bb1:
    _2 = _3;
    _4 = ((int32_t)(_2));
    _0 = _4;
    return _0;
}

int32_t sum__110(int64_t _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    const int64_t* _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    bool _7 __attribute__((unused)) = {0};
    const int64_t* _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    int32_t _10 __attribute__((unused)) = {0};
    int64_t _11 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _2 = 0;
    /* StorageLive(_3); */
    _3 = 0;
    /* StorageLive(_4); */
    _5 = (&_1);
    _6 = with_vec_len(_5);
    goto bb1;
bb1:
    _4 = _6;
    goto bb2;
bb2:
    _7 = (_3 < _4);
    if (_7 == 1) {
        goto bb3;
    }
    else {
        goto bb4;
    }
bb3:
    _8 = (&_1);
    _9 = with_vec_get_i32(_8, _3);
    goto bb5;
bb4:
    _0 = _2;
    return _0;
bb5:
    _10 = (_2 + _9);
    _2 = _10;
    _11 = (_3 + 1);
    _3 = _11;
    goto bb2;
}

int64_t map__114(int64_t _1, int64_t _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    const int64_t* _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    int64_t _7 __attribute__((unused)) = {0};
    const int64_t* _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    bool _10 __attribute__((unused)) = {0};
    with_str _11 __attribute__((unused)) = {0};
    const int64_t* _12 __attribute__((unused)) = {0};
    with_str _13 __attribute__((unused)) = {0};
    int32_t _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    const int64_t* _16 __attribute__((unused)) = {0};
    int32_t _17 __attribute__((unused)) = {0};
    int64_t _18 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    _3 = 0;
    _4 = (&_3);
    with_vec_new_out(_4, 4);
    goto bb1;
bb1:
    /* StorageLive(_6); */
    _6 = 0;
    /* StorageLive(_7); */
    _8 = (&_1);
    _9 = with_vec_len(_8);
    goto bb2;
bb2:
    _7 = _9;
    goto bb3;
bb3:
    _10 = (_6 < _7);
    if (_10 == 1) {
        goto bb4;
    }
    else {
        goto bb5;
    }
bb4:
    /* StorageLive(_11); */
    _12 = (&_1);
    _13 = with_vec_get_str(_12, _6);
    goto bb6;
bb5:
    _0 = _3;
    return;
bb6:
    _11 = _13;
    /* StorageLive(_14); */
    _15 = _2(_11);
    goto bb7;
bb7:
    _14 = _15;
    _16 = (&_3);
    with_vec_push_i32(_16, _14);
    goto bb8;
bb8:
    _18 = (_6 + 1);
    _6 = _18;
    goto bb3;
}

int64_t filter__117(int64_t _1, int64_t _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    const int64_t* _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    int64_t _7 __attribute__((unused)) = {0};
    const int64_t* _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    bool _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    const int64_t* _12 __attribute__((unused)) = {0};
    int32_t _13 __attribute__((unused)) = {0};
    bool _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    const int64_t* _16 __attribute__((unused)) = {0};
    int32_t _17 __attribute__((unused)) = {0};
    int64_t _18 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    _3 = 0;
    _4 = (&_3);
    with_vec_new_out(_4, 4);
    goto bb1;
bb1:
    /* StorageLive(_6); */
    _6 = 0;
    /* StorageLive(_7); */
    _8 = (&_1);
    _9 = with_vec_len(_8);
    goto bb2;
bb2:
    _7 = _9;
    goto bb3;
bb3:
    _10 = (_6 < _7);
    if (_10 == 1) {
        goto bb4;
    }
    else {
        goto bb5;
    }
bb4:
    /* StorageLive(_11); */
    _12 = (&_1);
    _13 = with_vec_get_i32(_12, _6);
    goto bb6;
bb5:
    _0 = _3;
    return;
bb6:
    _11 = _13;
    _14 = _2(_11);
    goto bb7;
bb7:
    if (_14 == 1) {
        goto bb8;
    }
    else {
        goto bb9;
    }
bb8:
    _16 = (&_3);
    with_vec_push_i32(_16, _11);
    goto bb11;
bb9:
    _15 = 0;
    goto bb10;
bb10:
    _18 = (_6 + 1);
    _6 = _18;
    goto bb3;
bb11:
    _15 = _17;
    goto bb10;
}

bool contains__120(int64_t _1, int32_t _2) {
    bool _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int32_t _6 __attribute__((unused)) = {0};
    int32_t _7 __attribute__((unused)) = {0};
    bool _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = _1;
    goto bb1;
bb1:
    _4 = sum__110(_3);
    goto bb4;
bb2:
    _6 = _4;
    /* StorageLive(_7); */
    _7 = _6;
    _8 = (_7 == _2);
    if (_8 == 1) {
        goto bb5;
    }
    else {
        goto bb6;
    }
bb3:
    _0 = false;
    return _0;
bb4:
    _5 = (_4).tag;
    if (_5 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb5:
    _0 = true;
    return _0;
bb6:
    _9 = 0;
    goto bb7;
bb7:
    goto bb1;
bb8:
    _9 = 0;
    goto bb7;
}

bool file_exists__128(with_str _1) {
    bool _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = with_vec_get_i32(_1, 0);
    goto bb1;
bb1:
    _3 = (_2 == 0);
    _0 = _3;
    return _0;
}

int32_t remove_file__130(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = string_len__77(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

int32_t rename_file__132(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = string_cmp__87(_1, _2);
    goto bb1;
bb1:
    _0 = _3;
    return _0;
}

int32_t create_dir__136(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    uint16_t _3 __attribute__((unused)) = {0};
    uint16_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _2 = 3;
    /* StorageLive(_3); */
    _4 = ((uint16_t)(_2));
    _3 = _4;
    _5 = with_vec_get_i32(_1, _3);
    goto bb1;
bb1:
    _0 = _5;
    return _0;
}

int32_t remove_dir__141(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = string_len__77(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

int32_t write_file__143(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = with_fs_write_file(_1, _2);
    goto bb1;
bb1:
    _0 = _3;
    return _0;
}

with_str read_file__144(with_str _1) {
    with_str _0 __attribute__((unused)) = {0};
    with_str _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = with_fs_read_file(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

void exit_code__160(int32_t _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    exit(_1);
    goto bb1;
bb1:
    _0 = _2;
    return;
}

int32_t system_cmd__161(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = system(_1);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

int32_t pid__162() {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _1 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    _1 = getpid();
    goto bb1;
bb1:
    _0 = _1;
    return _0;
}

int64_t args__163() {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _1 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    const int64_t* _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int32_t _6 __attribute__((unused)) = {0};
    bool _7 __attribute__((unused)) = {0};
    const int64_t* _8 __attribute__((unused)) = {0};
    with_str _9 __attribute__((unused)) = {0};
    int32_t _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = with_arg_count();
    goto bb1;
bb1:
    _1 = _2;
    /* StorageLive(_3); */
    _3 = 0;
    _4 = (&_3);
    with_vec_new_out(_4, 0);
    goto bb2;
bb2:
    /* StorageLive(_6); */
    _6 = 0;
    goto bb3;
bb3:
    _7 = (_6 < _1);
    if (_7 == 1) {
        goto bb4;
    }
    else {
        goto bb5;
    }
bb4:
    _8 = (&_3);
    _9 = with_arg_at(_6);
    goto bb6;
bb5:
    _0 = _3;
    return;
bb6:
    with_vec_push_str(_8, _9);
    goto bb7;
bb7:
    _11 = (_6 + 1);
    _6 = _11;
    goto bb3;
}

with_str env__164(with_str _1) {
    with_str _0 __attribute__((unused)) = {0};
    with_str _2 __attribute__((unused)) = {0};
    with_str _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    bool _5 __attribute__((unused)) = {0};
    with_str _6 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = with_getenv_str(_1);
    goto bb1;
bb1:
    _2 = _3;
    _4 = with_str_len(_2);
    goto bb2;
bb2:
    _5 = (_4 == 0);
    if (_5 == 1) {
        goto bb3;
    }
    else {
        goto bb4;
    }
bb3:
    _6 = WITH_STR_LIT("");
    goto bb5;
bb4:
    _6 = _2;
    goto bb5;
bb5:
    _0 = _6;
    return _0;
}

int32_t set_env__166(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    _3 = with_setenv_str(_1, _2);
    goto bb1;
bb1:
    _0 = _3;
    return _0;
}

Command command__168(with_str _1) {
    Command _0 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _0 = (Command){0};
    return _0;
}

int32_t Command_run__170(Command _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = system(_1.f149);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

int32_t Command_status__173(Command _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    /* StorageLive(_1); */
    _2 = system(_1.f149);
    goto bb1;
bb1:
    _0 = _2;
    return _0;
}

int main(int argc, char** argv) {
    with_runtime_set_argv(argc, argv);
    with_runtime_init();
    __with_main__1();
    with_runtime_shutdown();
    return 0;
}
