/* Generated by with --emit-c (conservative MIR subset). */
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include "with_runtime.h"

int64_t __with_main__1();
int64_t abs64__15(int64_t _1);
int64_t min64__21(int64_t _1, int64_t _2);
int64_t max64__22(int64_t _1, int64_t _2);
double sqrt_f64__26(double _1);
double pow_f64__29(double _1, double _2);
double floor_f64__33(double _1);
double ceil_f64__35(double _1);
double round_f64__37(double _1);
double sin_f64__39(double _1);
double cos_f64__41(double _1);
double tan_f64__43(double _1);
double log_f64__45(double _1);
double log10_f64__47(double _1);
double exp_f64__49(double _1);
double fabs_f64__50(double _1);
double fmod_f64__52(double _1, double _2);
double asin_f64__55(double _1);
double acos_f64__57(double _1);
double atan_f64__59(double _1);
double atan2_f64__61(double _1, double _2);
int64_t string_len__74(with_str _1);
int64_t view_len__77(const with_str* _1);
bool view_is_empty__80(const with_str* _1);
bool view_eq__82(const with_str* _1, const with_str* _2);
bool string_eq__83(with_str _1, with_str _2);
int32_t string_cmp__85(with_str _1, with_str _2);
bool is_alpha__87(int32_t _1);
bool is_digit__89(int32_t _1);
bool is_space__90(int32_t _1);
int64_t string_to_int__91(with_str _1);
int64_t lines__92(with_str _1);
int32_t parse__96(with_str _1);
int32_t sum__105(int64_t _1);
int64_t map__109(int64_t _1, int64_t _2);
int64_t filter__112(int64_t _1, int64_t _2);
bool contains__115(int64_t _1, int32_t _2);
bool file_exists__125(with_str _1);
int32_t remove_file__127(with_str _1);
int32_t rename_file__129(with_str _1, with_str _2);
int32_t create_dir__133(with_str _1);
int32_t remove_dir__138(with_str _1);
int32_t write_file__140(with_str _1, with_str _2);
with_str read_file__141(with_str _1);
void exit_code__156(int32_t _1);
int32_t system_cmd__157(with_str _1);
int32_t pid__158();
int64_t args__159();
with_str env__160(with_str _1);
int32_t set_env__162(with_str _1, with_str _2);
Command command__164(with_str _1);
int32_t Command_run__166(Command _1);
int32_t Command_status__169(Command _1);

int64_t __with_main__1() {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _1 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int64_t abs64__15(int64_t _1) {
    int64_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
}

int64_t min64__21(int64_t _1, int64_t _2) {
    int64_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
}

int64_t max64__22(int64_t _1, int64_t _2) {
    int64_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
}

double sqrt_f64__26(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double pow_f64__29(double _1, double _2) {
    double _0 __attribute__((unused)) = {0};
    double _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double floor_f64__33(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double ceil_f64__35(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double round_f64__37(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double sin_f64__39(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double cos_f64__41(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double tan_f64__43(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double log_f64__45(double _1) {
    double _0 __attribute__((unused)) = {0};
    bool _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double log10_f64__47(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double exp_f64__49(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double fabs_f64__50(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double fmod_f64__52(double _1, double _2) {
    double _0 __attribute__((unused)) = {0};
    double _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double asin_f64__55(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double acos_f64__57(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double atan_f64__59(double _1) {
    double _0 __attribute__((unused)) = {0};
    double _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

double atan2_f64__61(double _1, double _2) {
    double _0 __attribute__((unused)) = {0};
    double _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int64_t string_len__74(with_str _1) {
    int64_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int64_t view_len__77(const with_str* _1) {
    int64_t _0 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
}

bool view_is_empty__80(const with_str* _1) {
    bool _0 __attribute__((unused)) = {0};
    bool _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
}

bool view_eq__82(const with_str* _1, const with_str* _2) {
    bool _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
}

bool string_eq__83(with_str _1, with_str _2) {
    bool _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    bool _5 __attribute__((unused)) = {0};
    bool _6 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t string_cmp__85(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

bool is_alpha__87(int32_t _1) {
    bool _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int32_t _6 __attribute__((unused)) = {0};
    int32_t _7 __attribute__((unused)) = {0};
    bool _8 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
}

bool is_digit__89(int32_t _1) {
    bool _0 __attribute__((unused)) = {0};
    bool _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    bool _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
}

bool is_space__90(int32_t _1) {
    bool _0 __attribute__((unused)) = {0};
    bool _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    bool _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    bool _6 __attribute__((unused)) = {0};
    int32_t _7 __attribute__((unused)) = {0};
    bool _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    bool _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    bool _12 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
}

int64_t string_to_int__91(with_str _1) {
    int64_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int64_t lines__92(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t parse__96(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t sum__105(int64_t _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    int32_t _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    int32_t _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
bb4:
    abort();
bb5:
    abort();
}

int64_t map__109(int64_t _1, int64_t _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    int64_t _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    int32_t _10 __attribute__((unused)) = {0};
    with_str _11 __attribute__((unused)) = {0};
    int32_t _12 __attribute__((unused)) = {0};
    with_str _13 __attribute__((unused)) = {0};
    int32_t _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    int32_t _16 __attribute__((unused)) = {0};
    int32_t _17 __attribute__((unused)) = {0};
    int32_t _18 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
bb4:
    abort();
bb5:
    abort();
bb6:
    abort();
bb7:
    abort();
bb8:
    abort();
}

int64_t filter__112(int64_t _1, int64_t _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    int64_t _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    int32_t _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    int32_t _12 __attribute__((unused)) = {0};
    int32_t _13 __attribute__((unused)) = {0};
    int32_t _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    int32_t _16 __attribute__((unused)) = {0};
    int32_t _17 __attribute__((unused)) = {0};
    int32_t _18 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
bb4:
    abort();
bb5:
    abort();
bb6:
    abort();
bb7:
    abort();
bb8:
    abort();
bb9:
    abort();
bb10:
    abort();
bb11:
    abort();
}

bool contains__115(int64_t _1, int32_t _2) {
    bool _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int32_t _6 __attribute__((unused)) = {0};
    int32_t _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
bb4:
    abort();
bb5:
    abort();
bb6:
    abort();
bb7:
    abort();
bb8:
    abort();
}

bool file_exists__125(with_str _1) {
    bool _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    bool _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t remove_file__127(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t rename_file__129(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t create_dir__133(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    uint16_t _3 __attribute__((unused)) = {0};
    uint16_t _4 __attribute__((unused)) = {0};
    int64_t _5 __attribute__((unused)) = {0};
    int32_t _6 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t remove_dir__138(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t write_file__140(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

with_str read_file__141(with_str _1) {
    with_str _0 __attribute__((unused)) = {0};
    with_str _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

void exit_code__156(int32_t _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t system_cmd__157(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t pid__158() {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _1 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int64_t args__159() {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _1 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int32_t _6 __attribute__((unused)) = {0};
    int32_t _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    with_str _9 __attribute__((unused)) = {0};
    int32_t _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
bb4:
    abort();
bb5:
    abort();
bb6:
    abort();
bb7:
    abort();
}

with_str env__160(with_str _1) {
    with_str _0 __attribute__((unused)) = {0};
    with_str _2 __attribute__((unused)) = {0};
    with_str _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    with_str _6 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
bb2:
    abort();
bb3:
    abort();
bb4:
    abort();
bb5:
    abort();
}

int32_t set_env__162(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

Command command__164(with_str _1) {
    Command _0 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
}

int32_t Command_run__166(Command _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int32_t Command_status__169(Command _1) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    int32_t _3 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    abort();
bb1:
    abort();
}

int main(int argc, char** argv) {
    with_runtime_set_argv(argc, argv);
    with_runtime_init();
    __with_main__1();
    with_runtime_shutdown();
    return 0;
}
