#!/usr/bin/env bash
set -euo pipefail
# Convert runtime .o files to a data-only assembly object using .incbin.
# Missing objects produce empty start/end ranges so early bootstrap stages still
# build before the With runtime objects exist.

LIB_DIR="$1"
OUTPUT="$2"
count=0

escape_path() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

emit_blob() {
  local name="$1"
  local sym="$2"
  local ofile="${LIB_DIR}/${name}"

  echo ".globl _with_embedded_${sym}_start"
  echo ".globl with_embedded_${sym}_start"
  echo ".globl _with_embedded_${sym}_end"
  echo ".globl with_embedded_${sym}_end"
  echo ".p2align 4"
  echo "_with_embedded_${sym}_start:"
  echo "with_embedded_${sym}_start:"
  if [ -f "$ofile" ]; then
    local escaped
    escaped="$(escape_path "$ofile")"
    echo "    .incbin \"$escaped\""
    count=$((count + 1))
  fi
  echo "_with_embedded_${sym}_end:"
  echo "with_embedded_${sym}_end:"
  echo
}

{
  echo "// Auto-generated by embed_runtime_objects.sh — do not edit."
  echo ""
  if [ "$(uname -s)" = "Darwin" ]; then
    echo ".section __TEXT,__const"
    echo ".subsections_via_symbols"
  else
    echo ".section .rodata"
  fi
  echo ""
  emit_blob "cimport_stubs.o" "cimport_stubs_o"
  emit_blob "compat_runtime.o" "compat_runtime_o"
  emit_blob "panic_runtime.o" "panic_runtime_o"
  emit_blob "regex_runtime.o" "regex_runtime_o"
  emit_blob "fiber_stubs.o" "fiber_stubs_o"
  emit_blob "channel_runtime.o" "channel_runtime_o"
  emit_blob "fiber_runtime.o" "fiber_runtime_o"
  emit_blob "fiber.o" "fiber_o"
  emit_blob "fiber_asm.o" "fiber_asm_o"
  emit_blob "rt_core.o" "rt_core_o"
  emit_blob "rt_darwin_aarch64.o" "rt_darwin_aarch64_o"
} > "$OUTPUT"

echo "embedded ${count} runtime objects into ${OUTPUT}" >&2
