#!/usr/bin/env bash
set -euo pipefail
# Convert runtime .o files to C byte arrays using xxd.
# No Python dependency — uses only standard Unix tools.

LIB_DIR="$1"
OUTPUT="$2"
count=0

{
  echo "// Auto-generated by embed_runtime_objects.sh — do not edit."
  echo ""
  for name in helpers support_runtime with_runtime fiber fiber_asm rt_core rt_darwin_aarch64; do
    ofile="${LIB_DIR}/${name}.o"
    if [ -f "$ofile" ]; then
      size=$(wc -c < "$ofile" | tr -d ' ')
      echo "static const unsigned char ${name}_o[] = {"
      xxd -i < "$ofile"
      echo "};"
      echo "static const int ${name}_o_len = ${size};"
      count=$((count + 1))
    else
      echo "static const unsigned char ${name}_o[] = {0};"
      echo "static const int ${name}_o_len = 0;"
    fi
    echo ""
  done
} > "$OUTPUT"

echo "embedded ${count} runtime objects into ${OUTPUT}" >&2
