#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


def c_string_chunks(data: bytes, chunk_size: int = 1024) -> list[str]:
    chunks: list[str] = []
    for start in range(0, len(data), chunk_size):
        chunk = data[start : start + chunk_size]
        pieces: list[str] = []
        for b in chunk:
            if b == 0x5C:
                pieces.append("\\\\")
            elif b == 0x22:
                pieces.append('\\"')
            elif b == 0x0A:
                pieces.append("\\n")
            elif b == 0x0D:
                pieces.append("\\r")
            elif b == 0x09:
                pieces.append("\\t")
            elif 0x20 <= b <= 0x7E:
                pieces.append(chr(b))
            else:
                pieces.append(f"\\x{b:02x}")
                pieces.append('""')
        chunks.append('"' + "".join(pieces) + '"')
    return chunks or ['""']


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_embedded_stdlib.py <repo-root> <output-header>", file=sys.stderr)
        return 1

    root = Path(sys.argv[1]).resolve()
    out_path = Path(sys.argv[2]).resolve()
    std_root = root / "lib" / "std"
    files = sorted(std_root.rglob("*.w"))

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Auto-generated by scripts/generate_embedded_stdlib.py.\n")
        out.write("// Do not edit by hand.\n\n")
        out.write("static int with_embedded_std_eq(with_str path, const char *name, int64_t len) {\n")
        out.write("    return path.len == len && memcmp(path.ptr, name, (size_t)len) == 0;\n")
        out.write("}\n\n")
        out.write("with_str with_embedded_std_source(with_str path) {\n")
        for file_path in files:
            rel = file_path.relative_to(root / "lib").as_posix()
            data = file_path.read_bytes()
            chunks = c_string_chunks(data)
            out.write(f'    if (with_embedded_std_eq(path, "{rel}", {len(rel)})) {{\n')
            out.write("        return (with_str){\n")
            for chunk in chunks:
                out.write(f"            {chunk}\n")
            out.write(f"        , {len(data)} }};\n")
            out.write("    }\n")
        out.write('    return (with_str){ "", 0 };\n')
        out.write("}\n\n")

        # Generate module listing function for LSP completion.
        # Returns a newline-separated string of all embedded module relative paths.
        all_rels = []
        for file_path in files:
            rel = file_path.relative_to(root / "lib").as_posix()
            all_rels.append(rel)
        listing = "\\n".join(all_rels)
        out.write(f'with_str with_embedded_std_list_modules(void) {{\n')
        out.write(f'    return (with_str){{ "{listing}", {len(listing)} }};\n')
        out.write("}\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
