#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


def raw_string_literal(text: str) -> str:
    hash_count = 0
    while True:
        hashes = "#" * hash_count
        if f'"{hashes}' not in text:
            return f'r{hashes}"{text}"{hashes}'
        hash_count += 1


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_embedded_stdlib.py <repo-root> <output-file>", file=sys.stderr)
        return 1

    root = Path(sys.argv[1]).resolve()
    out_path = Path(sys.argv[2]).resolve()
    std_root = root / "lib" / "std"
    files = sorted(std_root.rglob("*.w"))

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Auto-generated by scripts/generate_embedded_stdlib.py.\n")
        out.write("// Do not edit by hand.\n\n")
        emitted: list[tuple[str, str]] = []
        for index, file_path in enumerate(files):
            rel = file_path.relative_to(root / "lib").as_posix()
            text = file_path.read_bytes().decode("utf-8")
            sym = f"EMBEDDED_STD_{index}"
            emitted.append((rel, sym))
            out.write(f"let {sym}: str = {raw_string_literal(text)}\n")
        listing = "\n".join(rel for rel, _ in emitted)
        out.write(f"let EMBEDDED_STD_MODULE_LIST: str = {raw_string_literal(listing)}\n\n")
        out.write('@[c_export("with_embedded_std_source")]\n')
        out.write("pub fn embedded_std_source(path: str) -> str:\n")
        for rel, sym in emitted:
            out.write(f"    if path == {raw_string_literal(rel)}:\n")
            out.write(f"        return {sym}\n")
        out.write('    return ""\n\n')

        # Generate module listing function for LSP completion.
        # Returns a newline-separated string of all embedded module relative paths.
        out.write('@[c_export("with_embedded_std_list_modules")]\n')
        out.write("pub fn embedded_std_list_modules() -> str:\n")
        out.write("    return EMBEDDED_STD_MODULE_LIST\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
