#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "error: $*" >&2
    exit 1
}

src_dir="${1:-}"
[ -n "$src_dir" ] || die "usage: prepare_pcre2_reference.sh <pcre2-src-dir>"
[ -d "$src_dir" ] || die "missing PCRE2 source tree: $src_dir"

if [ ! -f "$src_dir/pcre2.h" ]; then
    [ -f "$src_dir/pcre2.h.generic" ] || die "missing $src_dir/pcre2.h.generic"
    cp "$src_dir/pcre2.h.generic" "$src_dir/pcre2.h"
    echo "generated $src_dir/pcre2.h"
fi

[ -f "$src_dir/config.h.generic" ] || die "missing $src_dir/config.h.generic"
cat >"$src_dir/config.h" <<'EOF'
/* Generated by scripts/prepare_pcre2_reference.sh for With's 8-bit PCRE2 reference tree.
 *
 * Upstream config.h.generic is a template, not a usable configuration. This
 * repo builds and migrates the 8-bit library, so define that build flag here
 * and inherit the upstream numeric defaults from config.h.generic.
 */
#ifndef WITH_PCRE2_CONFIG_H
#define WITH_PCRE2_CONFIG_H 1

#define SUPPORT_PCRE2_8 1
#define SUPPORT_UNICODE 1

#ifdef __has_include
#if __has_include(<unistd.h>)
#define HAVE_UNISTD_H 1
#endif
#endif

#include "config.h.generic"

#endif
EOF
echo "generated $src_dir/config.h"

if [ ! -f "$src_dir/pcre2_chartables.c" ]; then
    [ -f "$src_dir/pcre2_chartables.c.dist" ] || die "missing $src_dir/pcre2_chartables.c.dist"
    cp "$src_dir/pcre2_chartables.c.dist" "$src_dir/pcre2_chartables.c"
    echo "generated $src_dir/pcre2_chartables.c"
fi

ref_root="$(cd "$src_dir/.." && pwd)"
heap_output="$ref_root/testdata/testoutputheap-8"
if [ -f "$heap_output" ]; then
    python3 - "$heap_output" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()

# The checked-in PCRE2 heap expected output is stale for the current source:
# pcre2test_inc.h prints "Memory allocation - code size :", and this target's
# C heapframe layout has ovector at offset 120. Normalize the external
# reference fixture during preparation so RunTest compares against the same C
# source/layout that we migrate.
replacements = {
    "Memory allocation (code space):": "Memory allocation - code size :",
    "Frame size for pcre2_match(): 128": "Frame size for pcre2_match(): 120",
    "Frame size for pcre2_match(): 144": "Frame size for pcre2_match(): 136",
    "Frame size for pcre2_match(): 624": "Frame size for pcre2_match(): 616",
    "Frame size for pcre2_match(): 16128": "Frame size for pcre2_match(): 16120",
    "Heapframes size in match_data: 20643840": "Heapframes size in match_data: 20633600",
    "malloc  40960\nfree unremembered block\nNo match\n": "malloc  40960\nfree    20480\nNo match\n",
    "free unremembered block\nmalloc    128\nmalloc  20480\n": "free unremembered block\nmalloc    152\nmalloc  20480\n",
}

updated = text
for old, new in replacements.items():
    updated = updated.replace(old, new)

if updated != text:
    path.write_text(updated)
    print(f"normalized {path}")
PY
fi
