#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "error: $*" >&2
    exit 1
}

src_dir="${1:-}"
[ -n "$src_dir" ] || die "usage: prepare_pcre2_reference.sh <pcre2-src-dir>"
[ -d "$src_dir" ] || die "missing PCRE2 source tree: $src_dir"

if [ ! -f "$src_dir/pcre2.h" ]; then
    [ -f "$src_dir/pcre2.h.generic" ] || die "missing $src_dir/pcre2.h.generic"
    cp "$src_dir/pcre2.h.generic" "$src_dir/pcre2.h"
    echo "generated $src_dir/pcre2.h"
fi

[ -f "$src_dir/config.h.generic" ] || die "missing $src_dir/config.h.generic"
cat >"$src_dir/config.h" <<'EOF'
/* Generated by scripts/prepare_pcre2_reference.sh for With's 8-bit PCRE2 reference tree.
 *
 * Upstream config.h.generic is a template, not a usable configuration. This
 * repo builds and migrates the 8-bit library, so define that build flag here
 * and inherit the upstream numeric defaults from config.h.generic.
 */
#ifndef WITH_PCRE2_CONFIG_H
#define WITH_PCRE2_CONFIG_H 1

#define SUPPORT_PCRE2_8 1

#ifdef __has_include
#if __has_include(<unistd.h>)
#define HAVE_UNISTD_H 1
#endif
#endif

#include "config.h.generic"

#endif
EOF
echo "generated $src_dir/config.h"

if [ ! -f "$src_dir/pcre2_chartables.c" ]; then
    [ -f "$src_dir/pcre2_chartables.c.dist" ] || die "missing $src_dir/pcre2_chartables.c.dist"
    cp "$src_dir/pcre2_chartables.c.dist" "$src_dir/pcre2_chartables.c"
    echo "generated $src_dir/pcre2_chartables.c"
fi
