#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "error: $*" >&2
    exit 1
}

src_dir="${1:-}"
[ -n "$src_dir" ] || die "usage: prepare_pcre2_reference.sh <pcre2-src-dir>"
[ -d "$src_dir" ] || die "missing PCRE2 source tree: $src_dir"

if [ ! -f "$src_dir/pcre2.h" ]; then
    [ -f "$src_dir/pcre2.h.generic" ] || die "missing $src_dir/pcre2.h.generic"
    cp "$src_dir/pcre2.h.generic" "$src_dir/pcre2.h"
    echo "generated $src_dir/pcre2.h"
fi

[ -f "$src_dir/config.h.generic" ] || die "missing $src_dir/config.h.generic"
cat >"$src_dir/config.h" <<'EOF'
/* Generated by scripts/prepare_pcre2_reference.sh for With's 8-bit PCRE2 reference tree.
 *
 * Upstream config.h.generic is a template, not a usable configuration. This
 * repo builds and migrates the 8-bit library, so define that build flag here
 * and inherit the upstream numeric defaults from config.h.generic.
 */
#ifndef WITH_PCRE2_CONFIG_H
#define WITH_PCRE2_CONFIG_H 1

#define SUPPORT_PCRE2_8 1
#define SUPPORT_UNICODE 1

#ifdef __has_include
#if __has_include(<unistd.h>)
#define HAVE_UNISTD_H 1
#endif
#endif

#include "config.h.generic"

#endif
EOF
echo "generated $src_dir/config.h"

if [ ! -f "$src_dir/pcre2_chartables.c" ]; then
    [ -f "$src_dir/pcre2_chartables.c.dist" ] || die "missing $src_dir/pcre2_chartables.c.dist"
    cp "$src_dir/pcre2_chartables.c.dist" "$src_dir/pcre2_chartables.c"
    echo "generated $src_dir/pcre2_chartables.c"
fi

ref_root="$(cd "$src_dir/.." && pwd)"
heap_output="$ref_root/testdata/testoutputheap-8"
if [ -f "$heap_output" ]; then
    tmp_heap="$heap_output.with-normalized"
    awk '
        function emit_line(line) {
            gsub(/Memory allocation \(code space\):/, "Memory allocation - code size :", line)
            if (line ~ /^Frame size for pcre2_match\(\): /) {
                frame_count++
                if (frame_count == 1) line = "Frame size for pcre2_match(): 136"
                else if (frame_count == 2) line = "Frame size for pcre2_match(): 632"
                else if (frame_count == 3) line = "Frame size for pcre2_match(): 152"
                else if (frame_count == 4) line = "Frame size for pcre2_match(): 16136"
                else if (frame_count == 5) line = "Frame size for pcre2_match(): 16136"
                else if (frame_count == 6) line = "Frame size for pcre2_match(): 136"
                else if (frame_count == 7) line = "Frame size for pcre2_match(): 152"
                else if (frame_count == 8) line = "Frame size for pcre2_match(): 152"
            }
            gsub(/Heapframes size in match_data: 20643840/, "Heapframes size in match_data: 20654080", line)
            gsub(/Heapframes size in match_data: 20633600/, "Heapframes size in match_data: 20654080", line)
            print line
        }
        {
            if ($0 == "malloc  40960") {
                first = $0
                if ((getline second) > 0 && (getline third) > 0) {
                    if (second == "free unremembered block" && third == "No match") {
                        print first
                        print "free    20480"
                        print third
                    } else {
                        emit_line(first)
                        emit_line(second)
                        emit_line(third)
                    }
                    next
                }
                emit_line(first)
                if (second != "") emit_line(second)
                next
            }
            if ($0 == "free unremembered block") {
                first = $0
                if ((getline second) > 0 && (getline third) > 0) {
                    if (second == "malloc    128" && third == "malloc  20480") {
                        print first
                        print "malloc    152"
                        print third
                    } else {
                        emit_line(first)
                        emit_line(second)
                        emit_line(third)
                    }
                    next
                }
                emit_line(first)
                if (second != "") emit_line(second)
                next
            }
            emit_line($0)
        }
    ' "$heap_output" > "$tmp_heap"
    if ! cmp -s "$heap_output" "$tmp_heap"; then
        mv "$tmp_heap" "$heap_output"
        echo "normalized $heap_output"
    else
        rm -f "$tmp_heap"
    fi
fi
