extern fn with_arg_count() -> i32
extern fn with_arg_at(idx: i32) -> str
extern fn with_fs_read_file(path: &str) -> str
extern fn with_fs_list_files(path: &str) -> str
extern fn with_fs_write_file(path: &str, data: &str) -> i32
extern fn with_eprint(s: &str) -> Unit
extern fn exit(code: i32) -> Unit

fn contains_delimiter(text: &str, hashes: &str) -> bool:
    let needle = "\"" ++ hashes
    if needle.len() == 0:
        return false
    if text.len() < needle.len():
        return false
    var i = 0
    while i <= text.len() as i32 - needle.len() as i32:
        var j = 0
        var matched = true
        while j < needle.len() as i32:
            if text[(i + j)] != needle[j]:
                matched = false
                break
            j += 1
        if matched:
            return true
        i += 1
    false

fn raw_string_literal(text: &str) -> str:
    var hashes = ""
    while contains_delimiter(text, hashes):
        hashes = hashes ++ "#"
    "r" ++ hashes ++ "\"" ++ text ++ "\"" ++ hashes

fn normalize_embedded_source(text: &str) -> str:
    var out = StringBuilder.with_capacity(text.len())
    var i = 0
    while i < text.len() as i32:
        let ch = text[i]
        if ch == 13:
            if i + 1 < text.len() as i32 and text[(i + 1)] == 10:
                i = i + 1
            out.push_byte(10 as u8)
        else:
            out.push_str(text.slice(i as i64, (i + 1) as i64))
        i = i + 1
    out.to_str()

fn embedded_rel_path(root: &str, path: &str) -> str:
    let root_lib = root ++ "/lib/"
    if path.starts_with(root_lib):
        return path.slice(root_lib.len(), path.len())
    if path.starts_with("lib/"):
        return path.slice(4, path.len())
    path

fn path_compare(a: &str, b: &str) -> i32:
    let min_len = if a.len() < b.len(): a.len() else: b.len()
    var i = 0
    while i < min_len as i32:
        let ac = a[i]
        let bc = b[i]
        if ac != bc:
            return ac - bc
        i = i + 1
    if a.len() == b.len(): return 0
    if a.len() < b.len(): return -1
    1

fn sort_paths(paths: Vec[str]):
    var sorted: Vec[str] = Vec.new()
    for i in 0..paths.len() as i32:
        let path = paths[i]
        var inserted = false
        var next: Vec[str] = Vec.new()
        for j in 0..sorted.len() as i32:
            let existing = sorted[j]
            if not inserted and path_compare(path, existing) < 0:
                next.push(path)
                inserted = true
            next.push(existing)
        if not inserted:
            next.push(path)
        sorted = next
    sorted

fn stdlib_tree_files(dir: &str):
    let listing = with_fs_list_files(dir)
    let excluded = dir ++ "/re/"
    var paths: Vec[str] = Vec.new()
    var start = 0
    for i in 0..listing.len() as i32 + 1:
        if i == listing.len() as i32 or listing[i] as i32 == 10:
            if i > start:
                let path = listing.slice(start as i64, i as i64)
                if path.ends_with(".w") and not path.starts_with(excluded):
                    paths.push(path)
            start = i + 1
    sort_paths(move paths)

fn usage: with_eprint("usage: generate_embedded_stdlib <repo-root> <output-file> <stdlib-files...> | --tree <repo-root> <output-file> <stdlib-dir>")

fn main:
    let argc = with_arg_count()
    if argc < 4:
        usage()
        exit(1)

    let tree_mode = with_arg_at(1) == "--tree"
    if tree_mode and argc != 5:
        usage()
        exit(1)
    let root = with_arg_at(if tree_mode: 2 else: 1)
    let out_path = with_arg_at(if tree_mode: 3 else: 2)
    var paths: Vec[str] = Vec.new()
    if tree_mode:
        paths = stdlib_tree_files(with_arg_at(4))
    else:
        for arg_i in 3..argc:
            paths.push(with_arg_at(arg_i))
    if paths.len() == 0:
        with_eprint("error: found no stdlib source files")
        exit(1)

    var out = StringBuilder.new()
    out.push_str("// Auto-generated by src/tools/generate_embedded_stdlib.w.\n")
    out.push_str("// Do not edit by hand.\n\n")

    var listing = StringBuilder.new()
    var i = 0
    var index = 0
    while i < paths.len() as i32:
        let path = paths[i]
        let rel = embedded_rel_path(root, path)
        let source = normalize_embedded_source(with_fs_read_file(path))
        if source.len() == 0:
            with_eprint("error: failed to read stdlib source: " ++ path)
            exit(1)
        let sym = f"EMBEDDED_STD_{index}"
        out.push_str("let ")
        out.push_str(sym)
        out.push_str(": str = ")
        out.push_str(raw_string_literal(source))
        out.push_str("\n")
        if listing.len() > 0:
            listing.push_str("\n")
        listing.push_str(rel)
        i += 1
        index += 1

    out.push_str("let EMBEDDED_STD_MODULE_LIST: str = ")
    out.push_str(raw_string_literal(listing.to_str()))
    out.push_str("\n\n")
    out.push_str("pub fn embedded_std_source_data(path: &str) -> str:\n")

    i = 0
    index = 0
    while i < paths.len() as i32:
        let path = paths[i]
        let rel = embedded_rel_path(root, path)
        let sym = f"EMBEDDED_STD_{index}"
        out.push_str("    if path == ")
        out.push_str(raw_string_literal(rel))
        out.push_str(":\n")
        out.push_str("        return ")
        out.push_str(sym)
        out.push_str("\n")
        i += 1
        index += 1

    out.push_str("    return \"\"\n\n")
    out.push_str("pub fn embedded_std_list_modules_data() -> str:\n")
    out.push_str("    return EMBEDDED_STD_MODULE_LIST\n")

    if with_fs_write_file(out_path, out.to_str()) != 0:
        with_eprint("error: failed to write " ++ out_path)
        exit(1)
