extern fn with_arg_count() -> i32
extern fn with_arg_at(idx: i32) -> str
extern fn with_fs_read_file(path: str) -> str
extern fn with_fs_write_file(path: str, data: str) -> i32
extern fn with_eprint(s: str) -> void
extern fn exit(code: i32) -> void

fn contains_delimiter(text: str, hashes: str) -> bool:
    let needle = "\"" ++ hashes
    if needle.len() == 0:
        return false
    if text.len() < needle.len():
        return false
    var i = 0
    while i <= text.len() as i32 - needle.len() as i32:
        var j = 0
        var matched = true
        while j < needle.len() as i32:
            if text.byte_at((i + j) as i64) != needle.byte_at(j as i64):
                matched = false
                break
            j += 1
        if matched:
            return true
        i += 1
    false

fn raw_string_literal(text: str) -> str:
    var hashes = ""
    while contains_delimiter(text, hashes):
        hashes = hashes ++ "#"
    "r" ++ hashes ++ "\"" ++ text ++ "\"" ++ hashes

fn embedded_rel_path(root: str, path: str) -> str:
    let root_lib = root ++ "/lib/"
    if path.starts_with(root_lib):
        return path.slice(root_lib.len(), path.len())
    if path.starts_with("lib/"):
        return path.slice(4, path.len())
    path

fn usage() -> void:
    with_eprint("usage: generate_embedded_stdlib <repo-root> <output-file> <stdlib-files...>")

fn main -> void:
    let argc = with_arg_count()
    if argc < 4:
        usage()
        exit(1)

    let root = with_arg_at(1)
    let out_path = with_arg_at(2)
    var out = StringBuilder.new()
    out.push_str("// Auto-generated by src/tools/generate_embedded_stdlib.w.\n")
    out.push_str("// Do not edit by hand.\n\n")

    var listing = StringBuilder.new()
    var i = 3
    var index = 0
    while i < argc:
        let path = with_arg_at(i)
        let rel = embedded_rel_path(root, path)
        let source = with_fs_read_file(path)
        if source.len() == 0:
            with_eprint("error: failed to read stdlib source: " ++ path)
            exit(1)
        let sym = f"EMBEDDED_STD_{index}"
        out.push_str("let ")
        out.push_str(sym)
        out.push_str(": str = ")
        out.push_str(raw_string_literal(source))
        out.push_str("\n")
        if listing.len() > 0:
            listing.push_str("\n")
        listing.push_str(rel)
        i += 1
        index += 1

    out.push_str("let EMBEDDED_STD_MODULE_LIST: str = ")
    out.push_str(raw_string_literal(listing.to_str()))
    out.push_str("\n\n")
    out.push_str("pub fn embedded_std_source_data(path: str) -> str:\n")

    i = 3
    index = 0
    while i < argc:
        let path = with_arg_at(i)
        let rel = embedded_rel_path(root, path)
        let sym = f"EMBEDDED_STD_{index}"
        out.push_str("    if path == ")
        out.push_str(raw_string_literal(rel))
        out.push_str(":\n")
        out.push_str("        return ")
        out.push_str(sym)
        out.push_str("\n")
        i += 1
        index += 1

    out.push_str("    return \"\"\n\n")
    out.push_str("pub fn embedded_std_list_modules_data() -> str:\n")
    out.push_str("    return EMBEDDED_STD_MODULE_LIST\n")

    if with_fs_write_file(out_path, out.to_str()) != 0:
        with_eprint("error: failed to write " ++ out_path)
        exit(1)
